"""Add news_posts table

Revision ID: 064db5df224a
Revises: 20260319_000001
Create Date: 2026-03-22 20:17:29.369575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '064db5df224a'
down_revision: Union[str, None] = '20260320_000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create news_posts only if it doesn't already exist (may have been created via Supabase)
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'news_posts')"
    ))
    if not result.scalar():
        op.create_table('news_posts',
        sa.Column('id', sa.String(length=128), nullable=False),
        sa.Column('slug', sa.String(length=512), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('subtitle', sa.Text(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('author', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=64), nullable=False),
        sa.Column('intro', sa.Text(), nullable=False),
        sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
        sa.Column('conclusion', sa.Text(), nullable=True),
        sa.Column('celebrity_name', sa.String(length=255), nullable=True),
        sa.Column('celebrity_profile_id', sa.String(length=128), nullable=True),
        sa.Column('celebrity_event', sa.Text(), nullable=True),
        sa.Column('meta_title', sa.Text(), nullable=True),
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('keywords', sa.Text(), nullable=True),
        sa.Column('og_image_url', sa.Text(), nullable=True),
        sa.Column('tags', sa.Text(), nullable=True),
        sa.Column('hero_image_url', sa.Text(), nullable=True),
        sa.Column('reddit_url', sa.Text(), nullable=True),
        sa.Column('reddit_subreddit', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
        )

    # Add columns only if they don't exist
    for col_name, col_type in [('tii', sa.Float()), ('tension_ratio', sa.Float()), ('feels_like', sa.String(length=64))]:
        res = conn.execute(sa.text(
            "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
            "WHERE table_name = 'latest_transits' AND column_name = :col)"
        ), {"col": col_name})
        if not res.scalar():
            op.add_column('latest_transits', sa.Column(col_name, col_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('latest_transits', 'feels_like')
    op.drop_column('latest_transits', 'tension_ratio')
    op.drop_column('latest_transits', 'tii')
    op.drop_table('news_posts')
    # ### end Alembic commands ###
