import Foundation

/// Every string the native screens show, in both languages.
///
/// Split into three tables per language and merged, rather than written as one
/// literal: a dictionary literal of several hundred entries is slow enough to
/// type-check that it shows up in build times.
///
/// Keys are shared with the web app's `frontend/src/i18n/{en,ru}.ts` wherever
/// the two say the same thing — `feels.*`, `mood.*`, `planet.*`, `sign.*`,
/// `aspect.*`, `strength.*`, `moon.*` — so a phrase translated once is
/// translated for both halves of the app. The rest are native-only screens.
enum Strings {

    static let en: [String: String] = merge(enUI, enAstro, enMood, enGuide)
    static let ru: [String: String] = merge(ruUI, ruAstro, ruMood, ruGuide)

    private static func merge(_ tables: [String: String]...) -> [String: String] {
        tables.reduce(into: [:]) { all, table in
            all.merge(table) { first, _ in first }
        }
    }
}

// MARK: - English

private let enUI: [String: String] = [
    // Common
    "common.done": "Done",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.ok": "OK",
    "common.tryAgain": "Try again",
    "common.delete": "Delete",
    "common.loading": "Loading",
    "common.today": "Today",
    "common.clear": "Clear",
    "common.notSet": "Not set",
    "common.day.one": "day",
    "common.day.few": "days",
    "common.day.many": "days",
    "common.year.one": "%d year",
    "common.year.few": "%d years",
    "common.year.many": "%d years",
    "common.dayCount.one": "%d day",
    "common.dayCount.few": "%d days",
    "common.dayCount.many": "%d days",
    "common.change.one": "%d change",
    "common.change.few": "%d changes",
    "common.change.many": "%d changes",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.notSignedIn": "Not signed in",
    "settings.signOut": "Sign out",
    "settings.accountFooter": "Deleting removes your profiles, birth data and the account itself. It cannot be undone.",
    "settings.deleteAccount": "Delete account",
    "settings.deleteAccountTitle": "Delete your account?",
    "settings.deleteAccountBody": "This removes your profiles, birth data, the people you follow and the account itself. It cannot be undone.",
    "settings.deleteAccountKeep": "Keep my account",
    "settings.deleteAccountFailed": "Could not delete the account",
    "settings.notifications": "Notifications",
    "settings.weatherAlerts": "Cosmic weather",
    "settings.cadence": "How often",
    "settings.cadence.changes": "On changes",
    "settings.cadence.daily": "Every day",
    "settings.openIosSettings": "Turn on in iOS Settings",
    "settings.timeOfDay": "Time of day",
    "settings.scheduled": "Scheduled",
    "settings.notificationsDenied": "Notifications are switched off for big3.me in iOS Settings, so nothing can be scheduled.",
    "settings.footerChanges": "Each day reads as one of twelve categories, from Calm to Explosive. A notification at this time on the days ahead when it moves to a different one, for the profile marked as yours. Quiet weeks stay quiet.",
    "settings.footerDaily": "Each day reads as one of twelve categories, from Calm to Explosive. A notification at this time every day, for the profile marked as yours, saying which one the day is.",
    "settings.nextAlert": "Next",
    "settings.sendTest": "Send a test notification",
    "settings.testAlert": "Test notification",
    "settings.testSent": "It arrives in a few seconds. Leave this screen to see the banner.",
    "settings.testFailed": "Nothing could be sent. Check that notifications are allowed for big3.me in iOS Settings.",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.theme.system": "System",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.language": "Language",
    "settings.language.system": "System",
    "settings.languageFooter": "System follows your device. The choice covers the whole app, the web screens included.",
    "settings.about": "About",
    "settings.version": "Version",

    // Sign in
    "auth.subtitleEmail": "Sign in with your email",
    "auth.subtitleCode": "We sent a code to %@",
    "auth.subtitlePassword": "Sign in with your password",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.code": "6-digit code",
    "auth.sendCode": "Send code",
    "auth.signIn": "Sign in",
    "auth.resend": "Resend",
    "auth.changeEmail": "Change email",
    "auth.or": "or",
    "auth.continueApple": "Continue with Apple",
    "auth.continueGoogle": "Continue with Google",
    "auth.usePassword": "Sign in with password",
    "auth.useCode": "Sign in with a code instead",
    "auth.checkInbox": "Check your inbox for the code.",

    // First-run offer of the category alerts
    "offer.title": "Know when the weather turns",
    "offer.body": "Each day reads as one of twelve categories, from Calm to Explosive. We'll tell you on the days ahead when it moves to a different one.",
    "offer.footnote": "Around midday. Settings can move the time, or ask for a word every day.",
    "offer.accept": "Turn them on",
    "offer.decline": "Not now",

    // Home
    "home.notSignedIn": "Not signed in",
    "home.notSignedInBody": "Sign in to see your forecast.",
    "home.openSignIn": "Open sign in",
    "home.loadFailed": "Could not load profiles",
    "home.noProfiles": "No profiles yet",
    "home.noProfilesBody": "Create a profile of your own, or find one to follow.",
    "home.createProfile": "Create profile",
    "home.searchProfiles": "Search profiles",
    "home.allProfiles": "All profiles",
    "home.pagerPosition": "Profile %1$d of %2$d",

    // Weather page
    "weather.editProfile": "Edit Profile",
    "weather.unfollow": "Unfollow",
    "weather.profileOptions": "Profile options",
    "weather.momentHint": "Choose the moment and place to read",
    // Under the hero's two numbers. Caps and small, so they name the numbers
    // without competing with them.
    "weather.intensityLabel": "INTENSITY",
    "weather.tensionLabel": "TENSION",
    // Spoken, and carried by the category alert: the word, never "TII".
    "weather.intensityValue": "Intensity %d",
    "weather.tensionA11y": "Tension %d percent",
    "weather.noForecast": "No forecast",
    "weather.noForecastDays": "No forecast days came back for this profile.",
    "weather.forecastTitle": "%d-day forecast",
    "forecast.todayLong": "Today, %@",
    "forecast.noTransits": "No transits",
    "forecast.noTransitsBody": "No transits inside orb on this day.",

    // Copy report — the profile's reading as Markdown, for pasting into a
    // chat model. The prompt is the first thing in the copied text rather
    // than a setting: whoever pastes it sees it in the chat window and can
    // rewrite it there, which is the one place they are already typing.
    "report.copy": "Copy report",
    "report.copied": "Report copied",
    "report.prompt": "Below is a finished astrological calculation: a natal chart and the transits for one moment, computed with Swiss Ephemeris, and a glossary of its two indices. These are positions, angles and intervals, not interpretations.\n\nReading them on their own terms means working from the actual aspects, their orbs, the houses they fall in and the windows they are inside, rather than from generic sign descriptions. Anything the data does not carry is not worth inventing.\n\nThese data can support, for example:\n1. What matters most right now: the two or three strongest transits, and why those.\n2. How they land on this particular chart rather than on a typical Aries.\n3. Timing: when it tightens, when it lets go.\n4. What to do about it in practice.\n\nWhat is useful is a conclusion rather than a retelling of the tables: a judgement resting on the numbers, and what follows from it.",
    "report.birth": "Born",
    "report.reading": "Read for",
    "report.now": "Right now",
    "report.intensity": "Intensity",
    "report.tension": "Tension",
    "report.weather": "Weather",
    "report.moon": "Moon",
    "report.retrograde": "Retrograde",
    "report.illumination": "%d%% lit",
    "report.of100": "%@ of 100",
    "report.glossary": "How to read the two numbers",
    "report.glossaryIntensity": "0 to 100. The summed weight of every transit currently inside orb of a natal planet, the ASC or the MC: each aspect's own weight (conjunction 10, opposition 8, square 7, trine 6, sextile 5) divided by its orb, scaled by the transiting body (Moon 0.5, Jupiter and Saturn 1.3, Uranus, Neptune and Pluto 1.5), with a bonus inside 1°. It measures how much is going on, not whether it is good. Bands: under 25 quiet, 25 to 55 active, 55 to 80 hot, 80 and up extreme.",
    "report.glossaryTension": "0 to 100%. The share of that same weight coming from hard aspects, meaning squares and oppositions. Under 30% low, 30 to 60% mixed, 60% and up high. High tension on low intensity is a quiet day that grinds; low tension on high intensity is a loud day that flows.",
    "report.glossaryWeather": "One label off the grid where those two meet, from Calm through Flowing to Explosive. It names the pair, it is not a third measurement.",
    "report.natal": "Natal chart",
    "report.houses": "House cusps",
    "report.natalAspects": "Natal aspects",
    "report.transits": "Active transits",
    "report.climate": "Long transits, the season behind the reading",
    "report.forecast": "The days ahead",
    "report.colObject": "Body",
    "report.colSign": "Sign",
    "report.colDegree": "Degree",
    "report.colHouse": "House",
    "report.colDate": "Date",
    "report.colIntensity": "Intensity",
    "report.colTension": "Tension",
    "report.colWeather": "Weather",
    "report.window": "window %1$@ to %2$@",
    "report.exact": "exact %@",

    // Active transits
    "transits.title": "Active transits",
    "transits.mostImpact": "Most impact",
    "transits.nothingStrong": "Nothing exact or strong right now.",
    "transits.orbA11y": "%1$@, %2$@, orb %3$@ degrees",
    "group.personal": "Personal planets",
    "group.outer": "Outer planets",
    "group.special": "Special points",

    // Climate
    "climate.title": "Climate",

    // Transit detail
    "detail.window": "Window",
    "detail.positions": "Positions",
    "detail.orb": "%@° orb",
    "detail.exactTimes": "Exact %1$d times: %2$@",
    "detail.hours": "%d h",
    "detail.days": "%d days",
    "detail.transiting": "transiting",
    "detail.natal": "natal",
    "detail.retrograde": "retrograde",
    "detail.house": "house %d",

    // Moment and place
    "moment.title": "Moment",
    "moment.date": "Date",
    "moment.time": "Time",
    "moment.place": "Place",
    "moment.searchCity": "Search city",
    "moment.profileOwn": "The profile's own",
    "moment.readPresent": "Read the present moment",
    "moment.readThis": "Read this moment",

    // Moon
    "moon.illumination": "Illumination",
    "moon.sign": "Moon sign",
    "moon.fullMoon": "Full moon",
    "moon.newMoon": "New moon",
    "moon.nextFullMoon": "Next full moon",

    // Natal chart card
    "natal.title": "Astro profile",
    "natal.expand": "Shows the rest of the profile",
    "natal.collapse": "Hides the rest of the profile",
    "natal.rowHint": "Opens this point in detail",
    "natal.transitsHere": "Transits to this point",

    // Natal aspect grid
    "natalAspects.title": "Chart aspects",
    "natalAspects.nothingStrong": "No exact or strong aspects in this chart.",

    // Compatibility (synastry). Keys shared with the web's own widget and
    // report, so the pair, the score labels and the four categories are
    // translated once for both halves of the app.
    "synastry.title": "Compatibility",
    "synastry.report": "Compatibility report",
    "synastry.choose": "Choose",
    "synastry.pickPrompt": "Pick someone to compare charts with",
    "synastry.pickTitle": "Choose a partner",
    "synastry.changePartner": "Change partner",
    "synastry.removePartner": "Remove partner",
    "synastry.partnerOptions": "Partner options",
    "synastry.openReport": "Open the report",
    "synastry.viewSynastry": "View compatibility",
    "synastry.noCandidates": "Follow someone, and their chart can be read against this one.",
    "synastry.findPeople": "Find people",
    "synastry.interAspects": "inter-aspects",
    "synastry.exactOrTight": "exact or tight",
    // Not the web's "Love": the same scoring reads as well between a parent
    // and a child, so the app does not assume the pair is a couple.
    "synastry.family": "Family",
    "synastry.business": "Business",
    "synastry.overallChemistry": "Overall chemistry:",
    "synastry.aspects": "COMPATIBILITY ASPECTS",
    "synastry.nothingStrong": "No exact or strong inter-aspects.",
    "synastry.scoreA11y": "Compatibility %1$d out of 100, %2$@",
    "synastry.emotional": "EMOTIONAL",
    "synastry.mental": "MENTAL",
    "synastry.physical": "PHYSICAL",
    "synastry.karmic": "KARMIC",
    "synastry.communication": "COMMUNICATION",
    "synastry.drive": "DRIVE",
    "synastry.trust": "TRUST",
    "synastry.vision": "VISION",

    // Chart wheel
    "chart.title": "Birth chart",
    "wheel.natal": "Birth",
    "wheel.transit": "Transit",
    "chart.wheelA11y": "Birth chart wheel",
    "chart.specialPoints": "Special points",
    "chart.tapHint": "Tap a planet or a line",
    "chart.tapHintZoom": "Tap a planet or a line · pinch to zoom",
    "chart.openFullScreen": "Open the chart full screen",
    "chart.fit": "Fit the whole chart",
    "chart.transit": "Transit",
    "chart.natal": "Natal",
    "chart.house": "House %d",
    "chart.orb": "orb %@",

    // Profile list
    "profiles.searchPrompt": "Search profiles",
    "profiles.mine": "Mine",
    "profiles.new": "New profile",
    "profiles.following": "Following",
    "profiles.primary": "Primary",
    "profiles.primaryA11y": "Primary profile",
    "profiles.none": "No profiles yet.",
    "profiles.noMatch": "Nothing matches “%@”.",
    "profiles.noReading": "No reading yet",

    // Profile search
    "search.title": "Search",
    "search.discover": "Discover",
    "search.new": "New profiles",
    "search.searching": "Searching…",
    "search.hint": "Search for a profile by name or @handle.",
    "search.followError": "Could not subscribe",
    "search.subscribeTo": "Subscribe to %@",
    "search.clear": "Clear search",
    "search.close": "Close search",

    // Profile preview
    "preview.bigThree": "Big 3",
    "preview.born": "Born",

    // Profile edit
    "edit.title": "Edit Profile",
    "edit.newTitle": "New Profile",
    "edit.save": "Save profile",
    "edit.name": "Name",
    "edit.fullName": "Full name",
    "edit.username": "Username",
    "edit.usernamePlaceholder": "username",
    "edit.date": "Date",
    "edit.time": "Time",
    "edit.birthplace": "Birthplace",
    "edit.birthplacePlaceholder": "City, country",
    "edit.pickPlace": "Pick a place from the list, or save and we will look this one up.",
    "edit.coordinates": "Coordinates & Timezone",
    "edit.coordinatesFooter": "These come from the birthplace you pick, so they are never typed by hand.",
    "edit.timezone": "Timezone",
    "edit.latitude": "Latitude",
    "edit.longitude": "Longitude",
    "edit.loadFailed": "Could not load this profile",
    "edit.deleteTitle": "Delete this profile?",
    "edit.deleteBody": "“%@” and its natal chart are removed for good. This cannot be undone.",
    "edit.deleteButton": "Delete Profile",
    "edit.resolveFailed": "Could not find “%@”. Pick a place from the list instead.",

    // Transfer a profile to someone else
    "transfer.title": "Transfer Profile",
    "transfer.sendTo": "Send to",
    "transfer.emailPlaceholder": "recipient@example.com",
    "transfer.profile": "Profile",
    "transfer.footer": "They get an email with a link. The profile stays yours until they sign in and accept it.",
    "transfer.send": "Send Invitation",
    "transfer.sending": "Sending",
    "transfer.sent": "Invitation sent",
    "transfer.created": "Invitation created",
    "transfer.sentBody": "%1$@ can now accept “%2$@”. It stays yours until they do.",
    "transfer.createdBody": "We could not send the email, so pass this link on yourself. It accepts “%@” for whoever opens it.",
    "transfer.copyLink": "Copy Link",
    "transfer.linkCopied": "Link Copied",
    "transfer.shareLink": "Share Link",

    // Category-change notifications
    "alert.rising": "Rising",
    "alert.easing": "Easing",
    "alert.shifting": "Shifting",
    "alert.steady": "Holding, same as yesterday",
    "alert.body": "%1$@ from %2$@",

    // Errors
    "error.notSignedIn": "Sign in to load your profiles.",
    "error.unexpected": "The server sent an unexpected response.",
    "error.cancelled": "The request was cancelled.",
    "error.googleNoSession": "Google sign-in returned without a session.",
    "error.appleNoToken": "Apple did not return an identity token.",
    "error.http": "Request failed (HTTP %d).",
    "error.tooMany": "Too many attempts. Wait a minute and try again.",
    "error.badDetails": "That did not work. Check the details and try again.",
    "error.noURL": "Could not build a URL for %@.",
]

private let enAstro: [String: String] = [
    "feels.Calm": "Calm",
    "feels.Subtle pressure": "Subtle pressure",
    "feels.Grinding": "Grinding",
    "feels.Flowing": "Flowing",
    "feels.Dynamic": "Dynamic",
    "feels.Pressured": "Pressured",
    "feels.Expansive": "Expansive",
    "feels.Charged": "Charged",
    "feels.Intense": "Intense",
    "feels.Powerful": "Powerful",
    "feels.Volatile": "Volatile",
    "feels.Explosive": "Explosive",

    "planet.Sun": "Sun",
    "planet.Moon": "Moon",
    "planet.Mercury": "Mercury",
    "planet.Venus": "Venus",
    "planet.Mars": "Mars",
    "planet.Jupiter": "Jupiter",
    "planet.Saturn": "Saturn",
    "planet.Uranus": "Uranus",
    "planet.Neptune": "Neptune",
    "planet.Pluto": "Pluto",
    "planet.Chiron": "Chiron",
    "planet.Lilith": "Lilith",
    "planet.Selena": "Selena",
    "planet.North Node": "North Node",
    "planet.South Node": "South Node",
    "planet.Part of Fortune": "Part of Fortune",
    "planet.Vertex": "Vertex",
    "planet.ASC": "Ascendant",
    "planet.MC": "Midheaven",

    "sign.Aries": "Aries",
    "sign.Taurus": "Taurus",
    "sign.Gemini": "Gemini",
    "sign.Cancer": "Cancer",
    "sign.Leo": "Leo",
    "sign.Virgo": "Virgo",
    "sign.Libra": "Libra",
    "sign.Scorpio": "Scorpio",
    "sign.Sagittarius": "Sagittarius",
    "sign.Capricorn": "Capricorn",
    "sign.Aquarius": "Aquarius",
    "sign.Pisces": "Pisces",

    "aspect.conjunction": "conjunction",
    "aspect.opposition": "opposition",
    "aspect.trine": "trine",
    "aspect.square": "square",
    "aspect.sextile": "sextile",

    "strength.exact": "EXACT",
    "strength.strong": "STRONG",
    "strength.moderate": "MODERATE",
    "strength.wide": "WIDE",

    "status.exact": "exact",
    "status.applying": "applying",
    "status.separating": "separating",

    "moon.New Moon": "New Moon",
    "moon.Waxing Crescent": "Waxing Crescent",
    "moon.First Quarter": "First Quarter",
    "moon.Waxing Gibbous": "Waxing Gibbous",
    "moon.Full Moon": "Full Moon",
    "moon.Waning Gibbous": "Waning Gibbous",
    "moon.Third Quarter": "Third Quarter",
    "moon.Last Quarter": "Last Quarter",
    "moon.Waning Crescent": "Waning Crescent",
]

/// The line under the feels-like label, per category and time of day. The
/// English and Russian halves of `data/feels_like_time_modifiers.json`, which
/// the web app reads directly; edits there belong here too.
private let enMood: [String: String] = [
    "mood.Calm.morning": "Gentle start ahead",
    "mood.Calm.afternoon": "Calm and steady",
    "mood.Calm.evening": "Peaceful wind-down",
    "mood.Calm.night": "Deep stillness",
    "mood.Subtle pressure.morning": "Something stirring beneath",
    "mood.Subtle pressure.afternoon": "Haze of tension",
    "mood.Subtle pressure.evening": "Undercurrent surfaces",
    "mood.Subtle pressure.night": "Restless quiet",
    "mood.Grinding.morning": "Heavy start, pace yourself",
    "mood.Grinding.afternoon": "Endurance mode",
    "mood.Grinding.evening": "Release the weight",
    "mood.Grinding.night": "Let the body recover",
    "mood.Flowing.morning": "Promising start",
    "mood.Flowing.afternoon": "In the flow",
    "mood.Flowing.evening": "Savor the harmony",
    "mood.Flowing.night": "Drift into peace",
    "mood.Dynamic.morning": "Active day building",
    "mood.Dynamic.afternoon": "Bold moves time",
    "mood.Dynamic.evening": "Process the buzz",
    "mood.Dynamic.night": "Mind still racing",
    "mood.Pressured.morning": "Brace for demands",
    "mood.Pressured.afternoon": "Adapt to pressure",
    "mood.Pressured.evening": "Decompress gently",
    "mood.Pressured.night": "Release and restore",
    "mood.Expansive.morning": "Big energy awakening",
    "mood.Expansive.afternoon": "Doors are opening",
    "mood.Expansive.evening": "Celebrate the expansion",
    "mood.Expansive.night": "Dream big tonight",
    "mood.Charged.morning": "Storm energy building",
    "mood.Charged.afternoon": "Ready to discharge",
    "mood.Charged.evening": "Let the charge settle",
    "mood.Charged.night": "Electric dreams ahead",
    "mood.Intense.morning": "Fiery day ahead",
    "mood.Intense.afternoon": "Fire and pressure",
    "mood.Intense.evening": "Cool the flames",
    "mood.Intense.night": "Let the fire die down",
    "mood.Powerful.morning": "Rare launch window",
    "mood.Powerful.afternoon": "Breakthrough energy",
    "mood.Powerful.evening": "Ride the momentum",
    "mood.Powerful.night": "Power in stillness",
    "mood.Volatile.morning": "Expect the unexpected",
    "mood.Volatile.afternoon": "Unpredictable shifts",
    "mood.Volatile.evening": "Ground after the storm",
    "mood.Volatile.night": "Turbulent dreams possible",
    "mood.Explosive.morning": "Maximum intensity day",
    "mood.Explosive.afternoon": "Everything at once",
    "mood.Explosive.evening": "Survive and reflect",
    "mood.Explosive.night": "Deep recovery needed",
]

// MARK: - Glossary

/// What every element of a reading means, in one line each.
///
/// The definitions are the web app's own — `guide.*` in
/// `frontend/src/i18n/{en,ru}.ts`, where they have been read inside the "How
/// It Works" sheet since it shipped — ported key for key, so a square is
/// defined the same way in both halves of the app and a phrase translated
/// once stays translated.
///
/// Definitions, never a reading. `about.*` is the native side's own: the
/// glue that names the parts of a sheet the web has no screen for, written to
/// the same rule — what the thing is, so the reader draws the conclusion.
private let enGuide: [String: String] = [
    // Section headings
    "about.transitTitle": "About this transit",
    "about.numbersTitle": "About the numbers",
    "about.windowTitle": "About the window",
    "about.positionsTitle": "About the positions",
    "about.pointTitle": "About this point",
    "about.chartAspectsTitle": "About chart aspects",
    "about.transitsHereTitle": "About transits to this point",
    "about.moonTitle": "About the Moon",
    "about.listsTitle": "About the two lists",

    // Transit and natal point
    "about.transitTerm": "Transit",
    "about.transitDesc": "A planet where it stands in the sky right now, at an angle to a point fixed in the birth chart. The chart never moves; the transit arrives, peaks and passes.",
    "about.transitingRole": "%@, the transiting planet",
    "about.natalRole": "%@, the natal point",
    "about.natalTerm": "Natal point",
    "about.natalDesc": "Where the point stood at the moment of birth. It does not move, and the transits come to it.",

    // Orb, strength, direction
    "about.orbTerm": "Orb",
    "about.orbDesc": "How far the angle is from exact, in degrees. 0° is a perfect hit, and the wider the orb the fainter the aspect.",
    "about.strengthTerm": "Strength",
    "about.strengthTransitDesc": "The orb read as a band: EXACT under 0.25°, STRONG under 1°, MODERATE under 2°, WIDE past that.",
    "about.strengthNatalDesc": "The orb read as a band: EXACT under 1°, STRONG under 3°, MODERATE under 5°, WIDE past that. A birth chart is banded wider than a transit because it never moves.",
    "about.statusTerm": "Applying and separating",
    "about.retrogradeNatalDesc": "Seen from Earth, the planet was moving backwards against the stars at the moment this chart was cast. It is part of the chart and never changes.",

    // Window
    "about.windowTerm": "Window",
    "about.windowDesc": "The stretch both points stay inside orb: from the day the aspect comes into range to the day it leaves it.",
    "about.exactTerm": "Exact",
    "about.exactDesc": "The moment the angle is perfect. A planet that turns retrograde inside the window crosses the same angle two or three times, so one window can hold several exact dates.",
    "about.barTerm": "The bar",
    "about.barDesc": "The arc is the whole window; the marker on it is where the day being read stands inside that window.",

    // Position
    "about.degreeTerm": "Degree and sign",
    "about.degreeDesc": "Where the point sits on the zodiac: the sign it is in, and how far into it, from 0°00′ to 29°59′.",
    "about.houseTerm": "House",
    "about.houseNumber": "House %d",
    "about.houseDesc": "One of the twelve slices of the chart, cut by the moment and the place of birth. A house is an area of life, and a point standing in it works through that area.",

    // Chart aspects
    "about.natalAspectTerm": "Chart aspect",
    "about.natalAspectDesc": "An angle between two points inside the birth chart itself. It was set at birth and never changes, unlike a transit, which passes.",

    // The day's numbers
    "about.intensityTerm": "Intensity",
    "about.zonesTerm": "Zones",
    "about.zonesDesc": "Quiet, 0 to 25: few aspects, or weak ones. Active, 25 to 55: several aspects engaging the chart. Hot, 55 to 80: many significant ones, some exact. Extreme, 80 and up: rare, several exact aspects including the outer planets.",
    "about.tensionTerm": "Tension",
    "about.tensionBandsTerm": "Bands",
    "about.tensionBandsDesc": "Low, 0 to 30%: mostly supportive aspects. Mixed, 30 to 60%: challenge and support in balance. High, 60 to 100%: challenging aspects dominate.",
    "about.feelsTerm": "Feels like",

    // Moon
    "about.moonPhaseTerm": "Phase",
    "about.moonPhaseDesc": "Where the Moon stands in its 29.5-day round from new to full and back.",
    "about.illuminationDesc": "How much of the Moon's disc is lit: 0% at the new Moon, 100% at the full.",
    "about.moonSignDesc": "The sign the Moon is travelling through right now. It moves on every two to three days, which makes it the fastest-changing line in the reading.",

    // Compatibility
    "about.synastryTitle": "About this report",
    "about.scoreTitle": "About the score",
    "about.aspectTableTitle": "About the aspect table",
    "about.synastryTerm": "Inter-aspect",
    "about.synastryDesc": "An angle between a point in one birth chart and a point in the other. Neither chart moves: the two are laid over each other and the angles between them measured.",
    "about.sidesTerm": "The two colours",
    "about.sidesDesc": "Every glyph and every name is tinted by whose chart it came from, which is the only thing on a row saying whose Moon meets whose Saturn.",
    "about.modeTerm": "Love and business",
    "about.modeDesc": "The same aspects, weighted twice. The love reading scores the bodies of feeling and attraction; the business one scores those of talk, drive, trust and vision.",
    "about.scoreTerm": "Score",
    "about.scoreDesc": "0 to 100: the share of the pair's weight coming from harmonious angles rather than hard ones, with the hard ones counted three times over so an easy chart does not flatter itself. Only aspects between the significant bodies count toward it.",
    "about.scoreBandsTerm": "Labels",
    "about.scoreBandsDesc": "86 and up Soulmate, 71 to 85 Magnetic, 51 to 70 Harmonious, 31 to 50 Complex, under 31 Challenging.",
    "about.categoriesTerm": "Categories",
    "about.loveCategoriesDesc": "The same score run over one slice of the pair each time. Emotional counts the aspects touching the Moon, Venus or Neptune; Mental those touching Mercury, Jupiter or Uranus; Physical the Sun, Mars or the Ascendant; Karmic Saturn, Pluto, the nodes, Lilith or Chiron.",
    "about.businessCategoriesDesc": "The same score run over one slice of the pair each time. Communication counts the aspects touching Mercury, Jupiter or the Moon; Drive those touching the Sun, Mars or the Midheaven; Trust Saturn, Pluto or the nodes; Vision Jupiter, Uranus or Neptune.",
    "about.mostImpactTerm": "Most impact",
    "about.mostImpactDesc": "Narrows the table to the exact and strong rows, which is everything inside 3° of the perfect angle.",
    "about.bandsTerm": "The three bands",
    "about.bandsDesc": "Rows are grouped by the more personal of the two bodies: personal planets are the Sun through Mars and the two angles, outer planets Jupiter through Pluto, special points everything else.",
    "about.strengthPairDesc": "The orb read as a band: EXACT under 1°, STRONG under 3°, MODERATE under 5°, WIDE past that. Two birth charts stand still against each other, so the bands are wider than a transit's.",

    // The two transit lists
    "about.activeTransitsDesc": "Every planet in the sky that is inside orb of a point in this chart on this day, tightest first.",
    "about.climateDesc": "The slow half of the same list: transits whose window runs for months rather than days, mostly from the outer planets.",

    // Planets and points
    "guide.sunDesc": "Your core identity, ego, vitality. What drives you.",
    "guide.moonDesc": "Emotions, instincts, inner world. How you feel.",
    "guide.mercuryDesc": "Communication, thinking, learning. How you process information.",
    "guide.venusDesc": "Love, beauty, values, money. What you attract.",
    "guide.marsDesc": "Action, drive, ambition, anger. How you pursue goals.",
    "guide.jupiterDesc": "Growth, luck, expansion, wisdom. Where life opens up.",
    "guide.saturnDesc": "Structure, discipline, limits, lessons. Where you must earn it.",
    "guide.uranusDesc": "Change, rebellion, innovation, surprises. Where you break free.",
    "guide.neptuneDesc": "Dreams, intuition, illusion, spirituality. Where boundaries dissolve.",
    "guide.plutoDesc": "Transformation, power, death/rebirth. Where you evolve deeply.",
    "guide.chironDesc": "Your deepest wound and healing gift.",
    "guide.lilithDesc": "Your shadow side. Suppressed power.",
    "guide.selenaDesc": "(White Moon) Your guardian angel point.",
    "guide.northNodeDesc": "Your karmic direction. Where you're growing toward.",
    "guide.southNodeDesc": "Your karmic past. What you're releasing.",
    "guide.pofDesc": "Where luck and talent naturally flow.",
    "guide.vertexDesc": "Fated encounters. Points of destiny.",
    "guide.ascendantDesc": "Your rising sign. The mask you wear. How others first perceive you.",
    "guide.descendantDesc": "Opposite your Ascendant. What you seek in partners and relationships.",
    "guide.midheavenDesc": "Top of the chart. Your career, public reputation, and life direction.",
    "guide.imumCoeliDesc": "Bottom of the chart. Your roots, home, private inner world.",

    // Signs
    "guide.ariesDesc": "Initiator. Bold, direct, competitive.",
    "guide.taurusDesc": "Builder. Patient, sensual, stubborn.",
    "guide.geminiDesc": "Communicator. Curious, adaptable, restless.",
    "guide.cancerDesc": "Nurturer. Emotional, protective, intuitive.",
    "guide.leoDesc": "Creator. Confident, dramatic, generous.",
    "guide.virgoDesc": "Analyst. Practical, precise, helpful.",
    "guide.libraDesc": "Diplomat. Harmonious, fair, indecisive.",
    "guide.scorpioDesc": "Transformer. Intense, deep, secretive.",
    "guide.sagittariusDesc": "Explorer. Optimistic, free, philosophical.",
    "guide.capricornDesc": "Achiever. Ambitious, disciplined, strategic.",
    "guide.aquariusDesc": "Innovator. Independent, humanitarian, eccentric.",
    "guide.piscesDesc": "Dreamer. Compassionate, imaginative, boundless.",

    // Aspects
    "guide.conjunctionDesc": "Fusion. Two planets merge energy. Powerful amplification. Neither easy nor hard, it depends on the planets involved.",
    "guide.sextileDesc": "Opportunity. Gentle support between planets. Talent that activates with small effort. Easy but requires initiative.",
    "guide.squareDesc": "Tension. Friction that forces action. Challenging but productive. The engine of growth. Creates results through pressure.",
    "guide.trineDesc": "Flow. Natural harmony between planets. Effortless talent. Can be so easy you take it for granted.",
    "guide.oppositionDesc": "Polarity. Two planets face each other. Awareness through contrast. Relationships, projection, finding balance.",
    "guide.aspectsNote": "Squares and oppositions are not \"bad.\" They create the tension that drives achievement. Trines and sextiles are not \"good.\" Without challenge, talent stays dormant.",

    // Houses
    "guide.house1": "Self, appearance, identity. How the world sees you. Your mask.",
    "guide.house2": "Money, possessions, values. What you own and what you value.",
    "guide.house3": "Communication, siblings, short trips. Daily interactions and learning.",
    "guide.house4": "Home, family, roots, privacy. Your foundation and inner sanctuary.",
    "guide.house5": "Creativity, romance, children, fun. What you create and enjoy.",
    "guide.house6": "Health, daily routines, work, service. How you maintain yourself.",
    "guide.house7": "Relationships, partnerships, marriage. The people who mirror you.",
    "guide.house8": "Transformation, shared resources, intimacy, death/rebirth. Deep merging.",
    "guide.house9": "Travel, philosophy, higher education, beliefs. Expanding your world.",
    "guide.house10": "Career, reputation, public image, ambition. Your legacy.",
    "guide.house11": "Friends, community, hopes, humanitarian goals. Your tribe.",
    "guide.house12": "Subconscious, spirituality, hidden enemies, isolation. What's invisible.",

    // Numbers and symbols
    "guide.applyingSep": "APPLYING means the aspect is getting tighter, building toward its peak. SEPARATING means it already peaked and is fading. Applying aspects are generally felt more strongly.",
    "guide.retrograde": "Retrograde",
    "guide.retrogradeDesc": "The planet appears to move backward. Energy turns inward, delays and revisions.",
    "about.intensityDesc": "How much planetary activity is landing on the birth chart, on a scale of 0 to 100. A thermometer for the day: the higher the number, the more is going on. It does not say whether that is good.",
    "about.tensionDesc": "The share of that activity coming from challenging aspects, squares and oppositions, rather than supportive ones, trines and sextiles. High tension does not mean bad: it means more friction, which can drive action and breakthroughs.",
    "about.feelsLikeDesc": "Just as weather has a \"feels like\" temperature, the two numbers are read together into one label. The same intensity feels very different depending on whether the energy flows or presses.",
]

// MARK: - Russian

private let ruUI: [String: String] = [
    // Common
    "common.done": "Готово",
    "common.cancel": "Отмена",
    "common.close": "Закрыть",
    "common.ok": "ОК",
    "common.tryAgain": "Повторить",
    "common.delete": "Удалить",
    "common.loading": "Загрузка",
    "common.today": "Сегодня",
    "common.clear": "Очистить",
    "common.notSet": "Не задан",
    "common.day.one": "день",
    "common.day.few": "дня",
    "common.day.many": "дней",
    "common.year.one": "%d год",
    "common.year.few": "%d года",
    "common.year.many": "%d лет",
    "common.dayCount.one": "%d день",
    "common.dayCount.few": "%d дня",
    "common.dayCount.many": "%d дней",
    "common.change.one": "%d смена",
    "common.change.few": "%d смены",
    "common.change.many": "%d смен",

    // Settings
    "settings.title": "Настройки",
    "settings.account": "Аккаунт",
    "settings.email": "Почта",
    "settings.notSignedIn": "Вход не выполнен",
    "settings.signOut": "Выйти",
    "settings.accountFooter": "Удаление убирает ваши профили, данные рождения и сам аккаунт. Отменить это нельзя.",
    "settings.deleteAccount": "Удалить аккаунт",
    "settings.deleteAccountTitle": "Удалить аккаунт?",
    "settings.deleteAccountBody": "Будут удалены ваши профили, данные рождения, подписки на других людей и сам аккаунт. Отменить это нельзя.",
    "settings.deleteAccountKeep": "Оставить аккаунт",
    "settings.deleteAccountFailed": "Не удалось удалить аккаунт",
    "settings.notifications": "Уведомления",
    "settings.weatherAlerts": "Космическая погода",
    "settings.cadence": "Как часто",
    "settings.cadence.changes": "При смене",
    "settings.cadence.daily": "Каждый день",
    "settings.openIosSettings": "Включить в настройках iOS",
    "settings.timeOfDay": "Время дня",
    "settings.scheduled": "Запланировано",
    "settings.notificationsDenied": "Уведомления для big3.me отключены в настройках iOS, поэтому запланировать их нельзя.",
    "settings.footerChanges": "Каждый день читается как одна из двенадцати категорий, от «Спокойно» до «Взрывоопасно». Уведомление в это время — в те дни, когда она сменится на другую, для профиля, отмеченного как ваш. В спокойные недели тихо.",
    "settings.footerDaily": "Каждый день читается как одна из двенадцати категорий, от «Спокойно» до «Взрывоопасно». Уведомление в это время каждый день, для профиля, отмеченного как ваш: какая категория у дня.",
    "settings.nextAlert": "Следующее",
    "settings.sendTest": "Отправить тестовое уведомление",
    "settings.testAlert": "Тестовое уведомление",
    "settings.testSent": "Придёт через несколько секунд. Выйдите с этого экрана, чтобы увидеть баннер.",
    "settings.testFailed": "Отправить не удалось. Проверьте, что уведомления для big3.me разрешены в настройках iOS.",
    "settings.appearance": "Оформление",
    "settings.theme": "Тема",
    "settings.theme.system": "Системная",
    "settings.theme.light": "Светлая",
    "settings.theme.dark": "Тёмная",
    "settings.language": "Язык",
    "settings.language.system": "Система",
    "settings.languageFooter": "«Система» берёт язык устройства. Выбор действует на всё приложение, включая веб-экраны.",
    "settings.about": "О приложении",
    "settings.version": "Версия",

    // Sign in
    "auth.subtitleEmail": "Войдите по электронной почте",
    "auth.subtitleCode": "Мы отправили код на %@",
    "auth.subtitlePassword": "Войдите с паролем",
    "auth.email": "Электронная почта",
    "auth.password": "Пароль",
    "auth.code": "Код из 6 цифр",
    "auth.sendCode": "Отправить код",
    "auth.signIn": "Войти",
    "auth.resend": "Отправить ещё раз",
    "auth.changeEmail": "Изменить адрес",
    "auth.or": "или",
    "auth.continueApple": "Продолжить с Apple",
    "auth.continueGoogle": "Продолжить с Google",
    "auth.usePassword": "Войти с паролем",
    "auth.useCode": "Войти по коду",
    "auth.checkInbox": "Проверьте почту, там код.",

    // First-run offer of the category alerts
    "offer.title": "Узнавайте, когда погода меняется",
    "offer.body": "Каждый день читается как одна из двенадцати категорий, от «Спокойно» до «Взрывоопасно». Мы скажем заранее о днях, когда она сменится на другую.",
    "offer.footnote": "Около полудня. В настройках можно сдвинуть время или просить сводку каждый день.",
    "offer.accept": "Включить",
    "offer.decline": "Не сейчас",

    // Home
    "home.notSignedIn": "Вход не выполнен",
    "home.notSignedInBody": "Войдите, чтобы увидеть свой прогноз.",
    "home.openSignIn": "Открыть вход",
    "home.loadFailed": "Не удалось загрузить профили",
    "home.noProfiles": "Профилей пока нет",
    "home.noProfilesBody": "Создайте свой профиль или найдите чужой, чтобы подписаться.",
    "home.createProfile": "Создать профиль",
    "home.searchProfiles": "Поиск профилей",
    "home.allProfiles": "Все профили",
    "home.pagerPosition": "Профиль %1$d из %2$d",

    // Weather page
    "weather.editProfile": "Изменить профиль",
    "weather.unfollow": "Отписаться",
    "weather.profileOptions": "Действия с профилем",
    "weather.momentHint": "Выберите момент и место для прогноза",
    "weather.intensityLabel": "ИНТЕНСИВНОСТЬ",
    "weather.tensionLabel": "НАПРЯЖЕНИЕ",
    "weather.intensityValue": "Интенсивность %d",
    "weather.tensionA11y": "Напряжение %d процентов",
    "weather.noForecast": "Прогноза нет",
    "weather.noForecastDays": "Для этого профиля не пришло ни одного дня прогноза.",
    "weather.forecastTitle": "Прогноз на %d дней",
    "forecast.todayLong": "Сегодня, %@",
    "forecast.noTransits": "Транзитов нет",
    "forecast.noTransitsBody": "В этот день нет транзитов в пределах орба.",

    // Copy report
    "report.copy": "Скопировать отчёт",
    "report.copied": "Отчёт скопирован",
    "report.prompt": "Ниже готовый астрологический расчёт: натальная карта и транзиты на указанный момент, Swiss Ephemeris, и глоссарий двух показателей. Это позиции, углы и интервалы, а не толкования.\n\nРазбор по существу опирается на конкретные аспекты, их орбы, дома и окна действия, а не на общие описания знаков. Чего в данных нет, того не стоит придумывать.\n\nНапример, по этим данным можно разобрать:\n1. Что сейчас главное: два-три самых сильных транзита и почему именно они.\n2. Как это ложится на эту конкретную карту, а не на «типичного Овна».\n3. Тайминг: когда усиливается, когда отпускает.\n4. Что с этим делать на практике.\n\nЦенен вывод, а не пересказ таблиц: суждение, опирающееся на числа, и то, что из него следует.",
    "report.birth": "Рождение",
    "report.reading": "Расчёт на",
    "report.now": "Сейчас",
    "report.intensity": "Интенсивность",
    "report.tension": "Напряжение",
    "report.weather": "Погода",
    "report.moon": "Луна",
    "report.retrograde": "Ретроградны",
    "report.illumination": "освещена на %d%%",
    "report.of100": "%@ из 100",
    "report.glossary": "Как читать два показателя",
    "report.glossaryIntensity": "От 0 до 100. Сумма веса всех транзитов, которые сейчас в орбе к натальной планете, к ASC или к MC: вес самого аспекта (соединение 10, оппозиция 8, квадрат 7, трин 6, секстиль 5), делённый на орб, с поправкой на транзитную планету (Луна 0.5, Юпитер и Сатурн 1.3, Уран, Нептун и Плутон 1.5) и надбавкой внутри 1°. Это мера того, сколько всего происходит, а не оценка «хорошо или плохо». Полосы: до 25 тихо, от 25 до 55 активно, от 55 до 80 горячо, от 80 предельно.",
    "report.glossaryTension": "От 0 до 100%. Какая доля того же веса приходится на жёсткие аспекты, то есть на квадраты и оппозиции. До 30% мало, от 30 до 60% смешанно, от 60% много. Высокое напряжение при низкой интенсивности это тихий день, который давит; низкое напряжение при высокой интенсивности это громкий день, который несёт.",
    "report.glossaryWeather": "Ярлык из таблицы, где эти два показателя пересекаются: от «Спокойно» через «Поток» до «Взрывоопасно». Он называет пару чисел, а не добавляет третье измерение.",
    "report.natal": "Натальная карта",
    "report.houses": "Куспиды домов",
    "report.natalAspects": "Натальные аспекты",
    "report.transits": "Активные транзиты",
    "report.climate": "Долгие транзиты, фон под прогнозом",
    "report.forecast": "Дни вперёд",
    "report.colObject": "Объект",
    "report.colSign": "Знак",
    "report.colDegree": "Градус",
    "report.colHouse": "Дом",
    "report.colDate": "Дата",
    "report.colIntensity": "Интенсивность",
    "report.colTension": "Напряжение",
    "report.colWeather": "Погода",
    "report.window": "окно с %1$@ по %2$@",
    "report.exact": "точно %@",

    // Active transits
    "transits.title": "Активные транзиты",
    "transits.mostImpact": "Самые сильные",
    "transits.nothingStrong": "Сейчас нет точных и сильных аспектов.",
    "transits.orbA11y": "%1$@, %2$@, орб %3$@ градусов",
    "group.personal": "Персональные планеты",
    "group.outer": "Высшие планеты",
    "group.special": "Особые точки",

    // Climate
    "climate.title": "Климат",

    // Transit detail
    "detail.window": "Окно",
    "detail.positions": "Позиции",
    "detail.orb": "орб %@°",
    "detail.exactTimes": "Точный %1$d раза: %2$@",
    "detail.hours": "%d ч",
    "detail.days": "%d дн.",
    "detail.transiting": "транзитная",
    "detail.natal": "натальная",
    "detail.retrograde": "ретроград",
    "detail.house": "дом %d",

    // Moment and place
    "moment.title": "Момент",
    "moment.date": "Дата",
    "moment.time": "Время",
    "moment.place": "Место",
    "moment.searchCity": "Поиск города",
    "moment.profileOwn": "Как у профиля",
    "moment.readPresent": "Читать текущий момент",
    "moment.readThis": "Читать этот момент",

    // Moon
    "moon.illumination": "Освещённость",
    "moon.sign": "Луна в знаке",
    "moon.fullMoon": "Полнолуние",
    "moon.newMoon": "Новолуние",
    "moon.nextFullMoon": "След. полнолуние",

    // Natal chart card
    "natal.title": "Астропрофиль",
    "natal.expand": "Показывает остальной профиль",
    "natal.collapse": "Скрывает остальной профиль",
    "natal.rowHint": "Открывает подробности точки",
    "natal.transitsHere": "Транзиты к этой точке",

    // Natal aspect grid
    "natalAspects.title": "Аспекты карты",
    "natalAspects.nothingStrong": "В этой карте нет точных и сильных аспектов.",

    // Совместимость
    "synastry.title": "Совместимость",
    "synastry.report": "Отчёт совместимости",
    "synastry.choose": "Выбрать",
    "synastry.pickPrompt": "Выберите, с кем сравнить карты",
    "synastry.pickTitle": "Выбор партнёра",
    "synastry.changePartner": "Сменить партнёра",
    "synastry.removePartner": "Убрать партнёра",
    "synastry.partnerOptions": "Действия с партнёром",
    "synastry.openReport": "Открыть отчёт",
    "synastry.viewSynastry": "Смотреть совместимость",
    "synastry.noCandidates": "Подпишитесь на кого-нибудь, и его карту можно будет сравнить с этой.",
    "synastry.findPeople": "Найти людей",
    "synastry.interAspects": "межаспектов",
    "synastry.exactOrTight": "точных или сильных",
    "synastry.family": "Семья",
    "synastry.business": "Бизнес",
    "synastry.overallChemistry": "Общая химия:",
    "synastry.aspects": "АСПЕКТЫ СОВМЕСТИМОСТИ",
    "synastry.nothingStrong": "Нет точных и сильных межаспектов.",
    "synastry.scoreA11y": "Совместимость %1$d из 100, %2$@",
    "synastry.emotional": "ЭМОЦИИ",
    "synastry.mental": "РАЗУМ",
    "synastry.physical": "ФИЗИКА",
    "synastry.karmic": "КАРМА",
    "synastry.communication": "ОБЩЕНИЕ",
    "synastry.drive": "ДРАЙВ",
    "synastry.trust": "ДОВЕРИЕ",
    "synastry.vision": "ВИДЕНИЕ",

    // Chart wheel
    "chart.title": "Карта рождения",
    "wheel.natal": "Рождение",
    "wheel.transit": "Транзит",
    "chart.wheelA11y": "Колесо карты рождения",
    "chart.specialPoints": "Особые точки",
    "chart.tapHint": "Нажмите на планету или линию",
    "chart.tapHintZoom": "Нажмите на планету или линию · щипок для зума",
    "chart.openFullScreen": "Открыть карту на весь экран",
    "chart.fit": "Показать карту целиком",
    "chart.transit": "Транзит",
    "chart.natal": "Карта",
    "chart.house": "Дом %d",
    "chart.orb": "орб %@",

    // Profile list
    "profiles.searchPrompt": "Поиск профилей",
    "profiles.mine": "Мои",
    "profiles.new": "Новый профиль",
    "profiles.following": "Подписки",
    "profiles.primary": "Основной",
    "profiles.primaryA11y": "Основной профиль",
    "profiles.none": "Профилей пока нет.",
    "profiles.noMatch": "Ничего не найдено по «%@».",
    "profiles.noReading": "Прогноза пока нет",

    // Profile search
    "search.title": "Поиск",
    "search.discover": "Интересное",
    "search.new": "Новые профили",
    "search.searching": "Поиск…",
    "search.hint": "Найдите профиль по имени или @нику.",
    "search.followError": "Не удалось подписаться",
    "search.subscribeTo": "Подписаться на %@",
    "search.clear": "Очистить поиск",
    "search.close": "Закрыть поиск",

    // Profile preview
    "preview.bigThree": "Большая тройка",
    "preview.born": "Рождение",

    // Profile edit
    "edit.title": "Изменить профиль",
    "edit.newTitle": "Новый профиль",
    "edit.save": "Сохранить профиль",
    "edit.name": "Имя",
    "edit.fullName": "Полное имя",
    "edit.username": "Ник",
    "edit.usernamePlaceholder": "ник",
    "edit.date": "Дата",
    "edit.time": "Время",
    "edit.birthplace": "Место рождения",
    "edit.birthplacePlaceholder": "Город, страна",
    "edit.pickPlace": "Выберите место из списка или сохраните, и мы найдём его сами.",
    "edit.coordinates": "Координаты и часовой пояс",
    "edit.coordinatesFooter": "Они берутся из выбранного места рождения, поэтому их не нужно вводить вручную.",
    "edit.timezone": "Часовой пояс",
    "edit.latitude": "Широта",
    "edit.longitude": "Долгота",
    "edit.loadFailed": "Не удалось загрузить профиль",
    "edit.deleteTitle": "Удалить этот профиль?",
    "edit.deleteBody": "«%@» и его натальная карта будут удалены навсегда. Отменить это нельзя.",
    "edit.deleteButton": "Удалить профиль",
    "edit.resolveFailed": "Не удалось найти «%@». Выберите место из списка.",

    // Transfer a profile to someone else
    "transfer.title": "Передать профиль",
    "transfer.sendTo": "Кому",
    "transfer.emailPlaceholder": "recipient@example.com",
    "transfer.profile": "Профиль",
    "transfer.footer": "Ему придёт письмо со ссылкой. Профиль остаётся вашим, пока он не войдёт и не примет его.",
    "transfer.send": "Отправить приглашение",
    "transfer.sending": "Отправка",
    "transfer.sent": "Приглашение отправлено",
    "transfer.created": "Приглашение создано",
    "transfer.sentBody": "%1$@ теперь может принять «%2$@». Профиль остаётся вашим, пока это не произойдёт.",
    "transfer.createdBody": "Письмо отправить не удалось, передайте ссылку сами. Она примет «%@» для того, кто её откроет.",
    "transfer.copyLink": "Скопировать ссылку",
    "transfer.linkCopied": "Ссылка скопирована",
    "transfer.shareLink": "Поделиться ссылкой",

    // Category-change notifications
    "alert.rising": "Растёт",
    "alert.easing": "Спадает",
    "alert.shifting": "Меняется",
    "alert.steady": "Держится, как вчера",
    "alert.body": "%1$@, было «%2$@»",

    // Errors
    "error.notSignedIn": "Войдите, чтобы загрузить профили.",
    "error.unexpected": "Сервер вернул неожиданный ответ.",
    "error.cancelled": "Запрос отменён.",
    "error.googleNoSession": "Вход через Google завершился без сессии.",
    "error.appleNoToken": "Apple не вернула токен для входа.",
    "error.http": "Запрос не удался (HTTP %d).",
    "error.tooMany": "Слишком много попыток. Подождите минуту и попробуйте снова.",
    "error.badDetails": "Не получилось. Проверьте данные и попробуйте снова.",
    "error.noURL": "Не удалось построить URL для %@.",
]

private let ruAstro: [String: String] = [
    "feels.Calm": "Спокойно",
    "feels.Subtle pressure": "Лёгкое давление",
    "feels.Grinding": "Тяжесть",
    "feels.Flowing": "Поток",
    "feels.Dynamic": "Динамично",
    "feels.Pressured": "Под давлением",
    "feels.Expansive": "Расширение",
    "feels.Charged": "Заряжено",
    "feels.Intense": "Интенсивно",
    "feels.Powerful": "Мощно",
    "feels.Volatile": "Нестабильно",
    "feels.Explosive": "Взрывоопасно",

    "planet.Sun": "Солнце",
    "planet.Moon": "Луна",
    "planet.Mercury": "Меркурий",
    "planet.Venus": "Венера",
    "planet.Mars": "Марс",
    "planet.Jupiter": "Юпитер",
    "planet.Saturn": "Сатурн",
    "planet.Uranus": "Уран",
    "planet.Neptune": "Нептун",
    "planet.Pluto": "Плутон",
    "planet.Chiron": "Хирон",
    "planet.Lilith": "Лилит",
    "planet.Selena": "Селена",
    "planet.North Node": "Сев. узел",
    "planet.South Node": "Юж. узел",
    "planet.Part of Fortune": "Жребий Фортуны",
    "planet.Vertex": "Вертекс",
    "planet.ASC": "Асцендент",
    "planet.MC": "Середина Неба",

    "sign.Aries": "Овен",
    "sign.Taurus": "Телец",
    "sign.Gemini": "Близнецы",
    "sign.Cancer": "Рак",
    "sign.Leo": "Лев",
    "sign.Virgo": "Дева",
    "sign.Libra": "Весы",
    "sign.Scorpio": "Скорпион",
    "sign.Sagittarius": "Стрелец",
    "sign.Capricorn": "Козерог",
    "sign.Aquarius": "Водолей",
    "sign.Pisces": "Рыбы",

    "aspect.conjunction": "соединение",
    "aspect.opposition": "оппозиция",
    "aspect.trine": "трин",
    "aspect.square": "квадрат",
    "aspect.sextile": "секстиль",

    "strength.exact": "ТОЧНЫЙ",
    "strength.strong": "СИЛЬНЫЙ",
    "strength.moderate": "УМЕРЕННЫЙ",
    "strength.wide": "СЛАБЫЙ",

    "status.exact": "точный",
    "status.applying": "сходится",
    "status.separating": "расходится",

    "moon.New Moon": "Новолуние",
    "moon.Waxing Crescent": "Растущий серп",
    "moon.First Quarter": "Первая четверть",
    "moon.Waxing Gibbous": "Растущая Луна",
    "moon.Full Moon": "Полнолуние",
    "moon.Waning Gibbous": "Убывающая Луна",
    "moon.Third Quarter": "Третья четверть",
    "moon.Last Quarter": "Последняя четверть",
    "moon.Waning Crescent": "Убывающий серп",
]

private let ruMood: [String: String] = [
    "mood.Calm.morning": "Мягкое начало дня",
    "mood.Calm.afternoon": "Спокойно и ровно",
    "mood.Calm.evening": "Спокойный вечер",
    "mood.Calm.night": "Глубокая тишина",
    "mood.Subtle pressure.morning": "Что-то шевелится внутри",
    "mood.Subtle pressure.afternoon": "Лёгкая дымка напряжения",
    "mood.Subtle pressure.evening": "Подводное течение всплывает",
    "mood.Subtle pressure.night": "Беспокойная тишина",
    "mood.Grinding.morning": "Тяжёлое начало, не спеши",
    "mood.Grinding.afternoon": "Режим выносливости",
    "mood.Grinding.evening": "Отпусти тяжесть",
    "mood.Grinding.night": "Дай телу восстановиться",
    "mood.Flowing.morning": "Многообещающее начало",
    "mood.Flowing.afternoon": "В потоке",
    "mood.Flowing.evening": "Насладись гармонией",
    "mood.Flowing.night": "Уплывай в покой",
    "mood.Dynamic.morning": "Активный день нарастает",
    "mood.Dynamic.afternoon": "Время смелых шагов",
    "mood.Dynamic.evening": "Переработай впечатления",
    "mood.Dynamic.night": "Мысли ещё гудят",
    "mood.Pressured.morning": "Готовься к нагрузке",
    "mood.Pressured.afternoon": "Адаптируйся к давлению",
    "mood.Pressured.evening": "Мягко сбрось давление",
    "mood.Pressured.night": "Отпусти и восстановись",
    "mood.Expansive.morning": "Большая энергия просыпается",
    "mood.Expansive.afternoon": "Двери открываются",
    "mood.Expansive.evening": "Отпразднуй расширение",
    "mood.Expansive.night": "Мечтай масштабно",
    "mood.Charged.morning": "Энергия грозы нарастает",
    "mood.Charged.afternoon": "Готово к разрядке",
    "mood.Charged.evening": "Дай заряду осесть",
    "mood.Charged.night": "Электрические сны впереди",
    "mood.Intense.morning": "Огненный день впереди",
    "mood.Intense.afternoon": "Огонь и давление",
    "mood.Intense.evening": "Остуди пламя",
    "mood.Intense.night": "Дай огню угаснуть",
    "mood.Powerful.morning": "Редкое окно запуска",
    "mood.Powerful.afternoon": "Энергия прорыва",
    "mood.Powerful.evening": "Используй импульс",
    "mood.Powerful.night": "Сила в покое",
    "mood.Volatile.morning": "Жди неожиданного",
    "mood.Volatile.afternoon": "Непредсказуемые сдвиги",
    "mood.Volatile.evening": "Заземлись после бури",
    "mood.Volatile.night": "Возможны бурные сны",
    "mood.Explosive.morning": "День максимальной интенсивности",
    "mood.Explosive.afternoon": "Всё сразу",
    "mood.Explosive.evening": "Выдохни и осмысли",
    "mood.Explosive.night": "Нужно глубокое восстановление",
]

private let ruGuide: [String: String] = [
    // Section headings
    "about.transitTitle": "Об этом транзите",
    "about.numbersTitle": "О числах",
    "about.windowTitle": "Об окне",
    "about.positionsTitle": "О позициях",
    "about.pointTitle": "Об этой точке",
    "about.chartAspectsTitle": "Об аспектах карты",
    "about.transitsHereTitle": "О транзитах к этой точке",
    "about.moonTitle": "О Луне",
    "about.listsTitle": "О двух списках",

    // Transit and natal point
    "about.transitTerm": "Транзит",
    "about.transitDesc": "Планета там, где она стоит в небе прямо сейчас, под углом к точке, закреплённой в карте рождения. Карта не меняется: транзит приходит, доходит до пика и уходит.",
    "about.transitingRole": "%@, транзитная планета",
    "about.natalRole": "%@, натальная точка",
    "about.natalTerm": "Натальная точка",
    "about.natalDesc": "Где точка стояла в момент рождения. Она не движется, транзиты приходят к ней сами.",

    // Orb, strength, direction
    "about.orbTerm": "Орб",
    "about.orbDesc": "Насколько угол отличается от точного, в градусах. 0° это идеальное попадание, и чем шире орб, тем слабее аспект.",
    "about.strengthTerm": "Сила",
    "about.strengthTransitDesc": "Орб, разложенный по полосам: ТОЧНЫЙ до 0.25°, СИЛЬНЫЙ до 1°, УМЕРЕННЫЙ до 2°, СЛАБЫЙ дальше.",
    "about.strengthNatalDesc": "Орб, разложенный по полосам: ТОЧНЫЙ до 1°, СИЛЬНЫЙ до 3°, УМЕРЕННЫЙ до 5°, СЛАБЫЙ дальше. У карты рождения полосы шире, чем у транзита, потому что она не меняется.",
    "about.statusTerm": "Сходится и расходится",
    "about.retrogradeNatalDesc": "В момент, на который построена карта, планета с Земли выглядела движущейся назад относительно звёзд. Это часть карты, и это не меняется.",

    // Window
    "about.windowTerm": "Окно",
    "about.windowDesc": "Отрезок, пока обе точки в пределах орба: от дня, когда аспект входит в диапазон, до дня, когда выходит.",
    "about.exactTerm": "Точный момент",
    "about.exactDesc": "Момент, когда угол идеален. Планета, уходящая в ретроград внутри окна, проходит тот же угол два или три раза, поэтому в одном окне бывает несколько точных дат.",
    "about.barTerm": "Полоса",
    "about.barDesc": "Дуга это всё окно, а метка на ней показывает, где внутри окна стоит читаемый день.",

    // Position
    "about.degreeTerm": "Градус и знак",
    "about.degreeDesc": "Где точка стоит в зодиаке: в каком знаке и как далеко внутри него, от 0°00′ до 29°59′.",
    "about.houseTerm": "Дом",
    "about.houseNumber": "%d-й дом",
    "about.houseDesc": "Один из двенадцати секторов карты, нарезанных моментом и местом рождения. Дом это область жизни, и точка в нём действует через эту область.",

    // Chart aspects
    "about.natalAspectTerm": "Аспект карты",
    "about.natalAspectDesc": "Угол между двумя точками внутри самой карты рождения. Он задан при рождении и не меняется, в отличие от транзита, который проходит.",

    // The day's numbers
    "about.intensityTerm": "Интенсивность",
    "about.zonesTerm": "Зоны",
    "about.zonesDesc": "Тихо, от 0 до 25: аспектов мало или они слабые. Активно, от 25 до 55: карту задействуют несколько аспектов. Горячо, от 55 до 80: значимых много, часть точные. Предельно, от 80: редкость, несколько точных аспектов, включая высшие планеты.",
    "about.tensionTerm": "Напряжение",
    "about.tensionBandsTerm": "Полосы",
    "about.tensionBandsDesc": "Низкое, от 0 до 30%: в основном гармоничные аспекты. Смешанное, от 30 до 60%: вызов и поддержка в равновесии. Высокое, от 60 до 100%: преобладают напряжённые аспекты.",
    "about.feelsTerm": "Ощущается как",

    // Moon
    "about.moonPhaseTerm": "Фаза",
    "about.moonPhaseDesc": "Где Луна в своём круге длиной 29.5 суток: от новолуния к полнолунию и обратно.",
    "about.illuminationDesc": "Какая доля диска Луны освещена: 0% в новолуние, 100% в полнолуние.",
    "about.moonSignDesc": "Знак, по которому Луна идёт прямо сейчас. Она меняет его каждые два-три дня, поэтому это самая быстрая строка в прогнозе.",

    // Compatibility
    "about.synastryTitle": "Об этом отчёте",
    "about.scoreTitle": "Об оценке",
    "about.aspectTableTitle": "О таблице аспектов",
    "about.synastryTerm": "Меж-аспект",
    "about.synastryDesc": "Угол между точкой одной карты рождения и точкой другой. Ни одна карта не движется: их накладывают друг на друга и измеряют углы между ними.",
    "about.sidesTerm": "Два цвета",
    "about.sidesDesc": "Каждый глиф и каждое имя окрашены по тому, из чьей они карты. Это единственное, что в строке говорит, чья Луна встречает чей Сатурн.",
    "about.modeTerm": "Любовь и бизнес",
    "about.modeDesc": "Одни и те же аспекты, взвешенные дважды. В любовном чтении считаются тела чувства и притяжения, в деловом тела разговора, воли, доверия и видения.",
    "about.scoreTerm": "Оценка",
    "about.scoreDesc": "От 0 до 100: какая доля веса пары приходится на гармоничные углы, а не на жёсткие, причём жёсткие считаются втрое, чтобы лёгкая карта себе не льстила. В счёт идут только аспекты между значимыми телами.",
    "about.scoreBandsTerm": "Ярлыки",
    "about.scoreBandsDesc": "От 86 «Родственные души», 71 до 85 «Магнетизм», 51 до 70 «Гармония», 31 до 50 «Сложная связь», ниже 31 «Вызов».",
    "about.categoriesTerm": "Категории",
    "about.loveCategoriesDesc": "Та же оценка, посчитанная каждый раз по одному срезу пары. В эмоциональную идут аспекты, задевающие Луну, Венеру или Нептун; в ментальную Меркурий, Юпитер или Уран; в физическую Солнце, Марс или Асцендент; в кармическую Сатурн, Плутон, узлы, Лилит или Хирон.",
    "about.businessCategoriesDesc": "Та же оценка, посчитанная каждый раз по одному срезу пары. В коммуникацию идут аспекты, задевающие Меркурий, Юпитер или Луну; в драйв Солнце, Марс или Середину Неба; в доверие Сатурн, Плутон или узлы; в видение Юпитер, Уран или Нептун.",
    "about.mostImpactTerm": "Самые сильные",
    "about.mostImpactDesc": "Оставляет в таблице только точные и сильные строки, то есть всё в пределах 3° от идеального угла.",
    "about.bandsTerm": "Три группы",
    "about.bandsDesc": "Строки сгруппированы по более личному из двух тел: персональные планеты это от Солнца до Марса и две оси, высшие планеты от Юпитера до Плутона, особые точки всё остальное.",
    "about.strengthPairDesc": "Орб, разложенный по полосам: ТОЧНЫЙ до 1°, СИЛЬНЫЙ до 3°, УМЕРЕННЫЙ до 5°, СЛАБЫЙ дальше. Две карты рождения стоят друг против друга неподвижно, поэтому полосы шире, чем у транзита.",

    // The two transit lists
    "about.activeTransitsDesc": "Все планеты неба, которые в этот день находятся в орбе к точке этой карты, самые точные сверху.",
    "about.climateDesc": "Медленная половина того же списка: транзиты, окно которых длится месяцами, а не днями, в основном от высших планет.",

    // Planets and points
    "guide.sunDesc": "Твоя основная идентичность, эго, витальность. Что тебя движет.",
    "guide.moonDesc": "Эмоции, инстинкты, внутренний мир. Как ты чувствуешь.",
    "guide.mercuryDesc": "Общение, мышление, обучение. Как ты обрабатываешь информацию.",
    "guide.venusDesc": "Любовь, красота, ценности, деньги. Что ты притягиваешь.",
    "guide.marsDesc": "Действие, драйв, амбиции, гнев. Как ты достигаешь целей.",
    "guide.jupiterDesc": "Рост, удача, расширение, мудрость. Где жизнь раскрывается.",
    "guide.saturnDesc": "Структура, дисциплина, ограничения, уроки. Где нужно заслужить.",
    "guide.uranusDesc": "Перемены, бунт, инновации, сюрпризы. Где ты вырываешься.",
    "guide.neptuneDesc": "Мечты, интуиция, иллюзии, духовность. Где границы растворяются.",
    "guide.plutoDesc": "Трансформация, власть, смерть/перерождение. Где ты глубоко эволюционируешь.",
    "guide.chironDesc": "Твоя глубочайшая рана и дар исцеления.",
    "guide.lilithDesc": "Твоя теневая сторона. Подавленная сила.",
    "guide.selenaDesc": "(Белая Луна) Твоя точка ангела-хранителя.",
    "guide.northNodeDesc": "Твоё кармическое направление. Куда ты растёшь.",
    "guide.southNodeDesc": "Твоё кармическое прошлое. Что ты отпускаешь.",
    "guide.pofDesc": "Где удача и талант текут естественно.",
    "guide.vertexDesc": "Судьбоносные встречи. Точки предназначения.",
    "guide.ascendantDesc": "Твой восходящий знак. Маска, которую ты носишь. Как тебя воспринимают при первой встрече.",
    "guide.descendantDesc": "Напротив Асцендента. Что ты ищешь в партнёрах и отношениях.",
    "guide.midheavenDesc": "Вершина карты. Твоя карьера, публичная репутация и направление жизни.",
    "guide.imumCoeliDesc": "Основание карты. Твои корни, дом, личный внутренний мир.",

    // Signs
    "guide.ariesDesc": "Инициатор. Смелый, прямой, соревновательный.",
    "guide.taurusDesc": "Строитель. Терпеливый, чувственный, упрямый.",
    "guide.geminiDesc": "Коммуникатор. Любопытный, адаптивный, неугомонный.",
    "guide.cancerDesc": "Защитник. Эмоциональный, заботливый, интуитивный.",
    "guide.leoDesc": "Творец. Уверенный, яркий, щедрый.",
    "guide.virgoDesc": "Аналитик. Практичный, точный, полезный.",
    "guide.libraDesc": "Дипломат. Гармоничный, справедливый, нерешительный.",
    "guide.scorpioDesc": "Трансформатор. Интенсивный, глубокий, скрытный.",
    "guide.sagittariusDesc": "Исследователь. Оптимистичный, свободный, философский.",
    "guide.capricornDesc": "Достиженец. Амбициозный, дисциплинированный, стратегический.",
    "guide.aquariusDesc": "Новатор. Независимый, гуманитарный, эксцентричный.",
    "guide.piscesDesc": "Мечтатель. Сочувствующий, творческий, безграничный.",

    // Aspects
    "guide.conjunctionDesc": "Слияние. Две планеты объединяют энергию. Мощное усиление. Не лёгкий и не тяжёлый, всё зависит от планет.",
    "guide.sextileDesc": "Возможность. Мягкая поддержка между планетами. Талант, активирующийся с небольшим усилием. Легко, но требует инициативы.",
    "guide.squareDesc": "Напряжение. Трение, которое заставляет действовать. Сложный, но продуктивный. Двигатель роста. Результаты через давление.",
    "guide.trineDesc": "Поток. Естественная гармония между планетами. Талант без усилий. Может быть настолько лёгким, что принимаешь как должное.",
    "guide.oppositionDesc": "Полярность. Две планеты смотрят друг на друга. Осознание через контраст. Отношения, проекция, поиск баланса.",
    "guide.aspectsNote": "Квадраты и оппозиции не «плохие». Они создают напряжение, которое движет достижениями. Трины и секстили не «хорошие». Без вызова талант остаётся спящим.",

    // Houses
    "guide.house1": "Я, внешность, идентичность. Как мир тебя видит. Твоя маска.",
    "guide.house2": "Деньги, имущество, ценности. Чем ты владеешь и что ценишь.",
    "guide.house3": "Общение, братья и сёстры, короткие поездки. Повседневные взаимодействия и обучение.",
    "guide.house4": "Дом, семья, корни, уединение. Твой фундамент и внутреннее убежище.",
    "guide.house5": "Творчество, романтика, дети, развлечения. Что ты создаёшь и чем наслаждаешься.",
    "guide.house6": "Здоровье, повседневная рутина, работа, служение. Как ты поддерживаешь себя.",
    "guide.house7": "Отношения, партнёрства, брак. Люди, которые тебя отражают.",
    "guide.house8": "Трансформация, общие ресурсы, близость, смерть/перерождение. Глубокое слияние.",
    "guide.house9": "Путешествия, философия, высшее образование, верования. Расширение мира.",
    "guide.house10": "Карьера, репутация, публичный имидж, амбиции. Твоё наследие.",
    "guide.house11": "Друзья, сообщество, надежды, гуманитарные цели. Твоё племя.",
    "guide.house12": "Подсознание, духовность, скрытые враги, изоляция. Что невидимо.",

    // Numbers and symbols
    "guide.applyingSep": "СХОДИТСЯ означает, что аспект сжимается и набирает пик. РАСХОДИТСЯ означает, что пик уже пройден и аспект угасает. Сходящиеся аспекты обычно ощущаются сильнее.",
    "guide.retrograde": "Ретроградность",
    "guide.retrogradeDesc": "Планета кажется движущейся назад. Энергия обращается внутрь, задержки и пересмотры.",
    "about.intensityDesc": "Сколько планетарной активности приходится на карту рождения, по шкале от 0 до 100. Термометр дня: чем выше число, тем больше происходит. Хорошо это или плохо, число не говорит.",
    "about.tensionDesc": "Какая доля этой активности приходится на жёсткие аспекты, квадраты и оппозиции, а не на гармоничные, трины и секстили. Высокое напряжение не значит плохо: это больше трения, которое может двигать к действию и прорывам.",
    "about.feelsLikeDesc": "Как у погоды есть «ощущается как», два числа читаются вместе и складываются в один ярлык. Одна и та же интенсивность ощущается по-разному в зависимости от того, течёт энергия или давит.",
]
