import Foundation

/// Every string the native screens show, in both languages.
///
/// Split into three tables per language and merged, rather than written as one
/// literal: a dictionary literal of several hundred entries is slow enough to
/// type-check that it shows up in build times.
///
/// Keys are shared with the web app's `frontend/src/i18n/{en,ru}.ts` wherever
/// the two say the same thing — `feels.*`, `mood.*`, `planet.*`, `sign.*`,
/// `aspect.*`, `strength.*`, `moon.*` — so a phrase translated once is
/// translated for both halves of the app. The rest are native-only screens.
enum Strings {

    static let en: [String: String] = merge(enUI, enAstro, enMood)
    static let ru: [String: String] = merge(ruUI, ruAstro, ruMood)

    private static func merge(_ tables: [String: String]...) -> [String: String] {
        tables.reduce(into: [:]) { all, table in
            all.merge(table) { first, _ in first }
        }
    }
}

// MARK: - English

private let enUI: [String: String] = [
    // Common
    "common.done": "Done",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.ok": "OK",
    "common.tryAgain": "Try again",
    "common.delete": "Delete",
    "common.loading": "Loading",
    "common.today": "Today",
    "common.clear": "Clear",
    "common.notSet": "Not set",
    "common.day.one": "day",
    "common.day.few": "days",
    "common.day.many": "days",
    "common.year.one": "%d year",
    "common.year.few": "%d years",
    "common.year.many": "%d years",
    "common.change.one": "%d change",
    "common.change.few": "%d changes",
    "common.change.many": "%d changes",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.notSignedIn": "Not signed in",
    "settings.signOut": "Sign out",
    "settings.manageAccount": "Manage account",
    "settings.accountFooter": "Deleting removes your profiles, birth data and the account itself. It cannot be undone.",
    "settings.deleteAccount": "Delete account",
    "settings.deleteAccountTitle": "Delete your account?",
    "settings.deleteAccountBody": "This removes your profiles, birth data, the people you follow and the account itself. It cannot be undone.",
    "settings.deleteAccountKeep": "Keep my account",
    "settings.deleteAccountFailed": "Could not delete the account",
    "settings.notifications": "Notifications",
    "settings.categoryChanges": "Category changes",
    "settings.openIosSettings": "Turn on in iOS Settings",
    "settings.timeOfDay": "Time of day",
    "settings.scheduled": "Scheduled",
    "settings.notificationsDenied": "Notifications are switched off for big3.me in iOS Settings, so nothing can be scheduled.",
    "settings.notificationsFooter": "Each day reads as one of twelve categories, from Calm to Explosive. Get a notification on the days ahead when it moves to a different one, for the profile marked as yours.",
    "settings.nextAlert": "Next",
    "settings.sendTest": "Send a test notification",
    "settings.testAlert": "Test notification",
    "settings.testSent": "It arrives in a few seconds. Leave this screen to see the banner.",
    "settings.testFailed": "Nothing could be sent. Check that notifications are allowed for big3.me in iOS Settings.",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.theme.system": "System",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.language": "Language",
    "settings.language.system": "System",
    "settings.languageFooter": "System follows your device. The choice covers the whole app, the web screens included.",
    "settings.about": "About",
    "settings.version": "Version",

    // Sign in
    "auth.subtitleEmail": "Sign in with your email",
    "auth.subtitleCode": "We sent a code to %@",
    "auth.subtitlePassword": "Sign in with your password",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.code": "6-digit code",
    "auth.sendCode": "Send code",
    "auth.signIn": "Sign in",
    "auth.resend": "Resend",
    "auth.changeEmail": "Change email",
    "auth.or": "or",
    "auth.continueApple": "Continue with Apple",
    "auth.continueGoogle": "Continue with Google",
    "auth.usePassword": "Sign in with password",
    "auth.useCode": "Sign in with a code instead",
    "auth.checkInbox": "Check your inbox for the code.",

    // First-run offer of the category alerts
    "offer.title": "Know when the weather turns",
    "offer.body": "Each day reads as one of twelve categories, from Calm to Explosive. We'll tell you on the days ahead when it moves to a different one.",
    "offer.footnote": "Around midday, and only on the days it actually changes.",
    "offer.accept": "Turn them on",
    "offer.decline": "Not now",

    // Home
    "home.notSignedIn": "Not signed in",
    "home.notSignedInBody": "Sign in to see your forecast.",
    "home.openSignIn": "Open sign in",
    "home.loadFailed": "Could not load profiles",
    "home.noProfiles": "No profiles yet",
    "home.noProfilesBody": "Create a profile of your own, or find one to follow.",
    "home.createProfile": "Create profile",
    "home.searchProfiles": "Search profiles",
    "home.allProfiles": "All profiles",
    "home.pagerPosition": "Profile %1$d of %2$d",

    // Weather page
    "weather.editProfile": "Edit Profile",
    "weather.unfollow": "Unfollow",
    "weather.profileOptions": "Profile options",
    "weather.momentHint": "Choose the moment and place to read",
    // Under the hero's two numbers. Caps and small, so they name the numbers
    // without competing with them.
    "weather.intensityLabel": "INTENSITY",
    "weather.tensionLabel": "TENSION",
    // Spoken, and carried by the category alert: the word, never "TII".
    "weather.intensityValue": "Intensity %d",
    "weather.tensionA11y": "Tension %d percent",
    "weather.noForecast": "No forecast",
    "weather.noForecastDays": "No forecast days came back for this profile.",
    "weather.forecastTitle": "%d-day forecast",
    "forecast.todayLong": "Today, %@",
    "forecast.noTransits": "No transits",
    "forecast.noTransitsBody": "No transits inside orb on this day.",

    // Active transits
    "transits.title": "Active transits",
    "transits.mostImpact": "Most impact",
    "transits.nothingStrong": "Nothing exact or strong right now.",
    "transits.orbA11y": "%1$@, %2$@, orb %3$@ degrees",
    "group.personal": "Personal planets",
    "group.outer": "Outer planets",
    "group.special": "Special points",

    // Climate
    "climate.title": "Climate",

    // Transit detail
    "detail.window": "Window",
    "detail.positions": "Positions",
    "detail.orb": "%@° orb",
    "detail.exactTimes": "Exact %1$d times: %2$@",
    "detail.hours": "%d h",
    "detail.days": "%d days",
    "detail.transiting": "transiting",
    "detail.natal": "natal",
    "detail.retrograde": "retrograde",
    "detail.house": "house %d",

    // Moment and place
    "moment.title": "Moment",
    "moment.date": "Date",
    "moment.time": "Time",
    "moment.place": "Place",
    "moment.searchCity": "Search city",
    "moment.profileOwn": "The profile's own",
    "moment.readPresent": "Read the present moment",
    "moment.readThis": "Read this moment",

    // Moon
    "moon.illumination": "Illumination",
    "moon.sign": "Moon sign",
    "moon.fullMoon": "Full moon",
    "moon.newMoon": "New moon",
    "moon.nextFullMoon": "Next full moon",

    // Natal chart card
    "natal.title": "Astro profile",
    "natal.expand": "Shows the rest of the profile",
    "natal.collapse": "Hides the rest of the profile",

    // Chart wheel
    "chart.title": "Birth chart",
    "wheel.natal": "Birth",
    "wheel.transit": "Transit",
    "chart.wheelA11y": "Birth chart wheel",
    "chart.specialPoints": "Special points",
    "chart.tapHint": "Tap a planet or a line",
    "chart.tapHintZoom": "Tap a planet or a line · pinch to zoom",
    "chart.openFullScreen": "Open the chart full screen",
    "chart.fit": "Fit the whole chart",
    "chart.transit": "Transit",
    "chart.natal": "Natal",
    "chart.house": "House %d",
    "chart.orb": "orb %@",

    // Profile list
    "profiles.searchPrompt": "Search profiles",
    "profiles.mine": "Mine",
    "profiles.new": "New profile",
    "profiles.following": "Following",
    "profiles.primary": "Primary",
    "profiles.primaryA11y": "Primary profile",
    "profiles.none": "No profiles yet.",
    "profiles.noMatch": "Nothing matches “%@”.",
    "profiles.noReading": "No reading yet",

    // Profile search
    "search.title": "Search",
    "search.discover": "Discover",
    "search.new": "New profiles",
    "search.searching": "Searching…",
    "search.hint": "Search for a profile by name or @handle.",
    "search.followError": "Could not subscribe",
    "search.subscribeTo": "Subscribe to %@",
    "search.clear": "Clear search",
    "search.close": "Close search",

    // Profile preview
    "preview.bigThree": "Big 3",
    "preview.born": "Born",

    // Profile edit
    "edit.title": "Edit Profile",
    "edit.newTitle": "New Profile",
    "edit.save": "Save profile",
    "edit.name": "Name",
    "edit.fullName": "Full name",
    "edit.username": "Username",
    "edit.usernamePlaceholder": "username",
    "edit.date": "Date",
    "edit.time": "Time",
    "edit.birthplace": "Birthplace",
    "edit.birthplacePlaceholder": "City, country",
    "edit.pickPlace": "Pick a place from the list, or save and we will look this one up.",
    "edit.coordinates": "Coordinates & Timezone",
    "edit.coordinatesFooter": "These come from the birthplace you pick, so they are never typed by hand.",
    "edit.timezone": "Timezone",
    "edit.latitude": "Latitude",
    "edit.longitude": "Longitude",
    "edit.loadFailed": "Could not load this profile",
    "edit.deleteTitle": "Delete this profile?",
    "edit.deleteBody": "“%@” and its natal chart are removed for good. This cannot be undone.",
    "edit.deleteButton": "Delete Profile",
    "edit.resolveFailed": "Could not find “%@”. Pick a place from the list instead.",

    // Transfer a profile to someone else
    "transfer.title": "Transfer Profile",
    "transfer.sendTo": "Send to",
    "transfer.emailPlaceholder": "recipient@example.com",
    "transfer.profile": "Profile",
    "transfer.footer": "They get an email with a link. The profile stays yours until they sign in and accept it.",
    "transfer.send": "Send Invitation",
    "transfer.sending": "Sending",
    "transfer.sent": "Invitation sent",
    "transfer.created": "Invitation created",
    "transfer.sentBody": "%1$@ can now accept “%2$@”. It stays yours until they do.",
    "transfer.createdBody": "We could not send the email, so pass this link on yourself. It accepts “%@” for whoever opens it.",
    "transfer.copyLink": "Copy Link",
    "transfer.linkCopied": "Link Copied",
    "transfer.shareLink": "Share Link",

    // Category-change notifications
    "alert.rising": "Rising",
    "alert.easing": "Easing",
    "alert.shifting": "Shifting",
    "alert.body": "%1$@ from %2$@",

    // Errors
    "error.notSignedIn": "Sign in to load your profiles.",
    "error.unexpected": "The server sent an unexpected response.",
    "error.cancelled": "The request was cancelled.",
    "error.googleNoSession": "Google sign-in returned without a session.",
    "error.appleNoToken": "Apple did not return an identity token.",
    "error.http": "Request failed (HTTP %d).",
    "error.tooMany": "Too many attempts. Wait a minute and try again.",
    "error.badDetails": "That did not work. Check the details and try again.",
    "error.noURL": "Could not build a URL for %@.",
]

private let enAstro: [String: String] = [
    "feels.Calm": "Calm",
    "feels.Subtle pressure": "Subtle pressure",
    "feels.Grinding": "Grinding",
    "feels.Flowing": "Flowing",
    "feels.Dynamic": "Dynamic",
    "feels.Pressured": "Pressured",
    "feels.Expansive": "Expansive",
    "feels.Charged": "Charged",
    "feels.Intense": "Intense",
    "feels.Powerful": "Powerful",
    "feels.Volatile": "Volatile",
    "feels.Explosive": "Explosive",

    "planet.Sun": "Sun",
    "planet.Moon": "Moon",
    "planet.Mercury": "Mercury",
    "planet.Venus": "Venus",
    "planet.Mars": "Mars",
    "planet.Jupiter": "Jupiter",
    "planet.Saturn": "Saturn",
    "planet.Uranus": "Uranus",
    "planet.Neptune": "Neptune",
    "planet.Pluto": "Pluto",
    "planet.Chiron": "Chiron",
    "planet.Lilith": "Lilith",
    "planet.Selena": "Selena",
    "planet.North Node": "North Node",
    "planet.South Node": "South Node",
    "planet.Part of Fortune": "Part of Fortune",
    "planet.Vertex": "Vertex",
    "planet.ASC": "Ascendant",
    "planet.MC": "Midheaven",

    "sign.Aries": "Aries",
    "sign.Taurus": "Taurus",
    "sign.Gemini": "Gemini",
    "sign.Cancer": "Cancer",
    "sign.Leo": "Leo",
    "sign.Virgo": "Virgo",
    "sign.Libra": "Libra",
    "sign.Scorpio": "Scorpio",
    "sign.Sagittarius": "Sagittarius",
    "sign.Capricorn": "Capricorn",
    "sign.Aquarius": "Aquarius",
    "sign.Pisces": "Pisces",

    "aspect.conjunction": "conjunction",
    "aspect.opposition": "opposition",
    "aspect.trine": "trine",
    "aspect.square": "square",
    "aspect.sextile": "sextile",

    "strength.exact": "EXACT",
    "strength.strong": "STRONG",
    "strength.moderate": "MODERATE",
    "strength.wide": "WIDE",

    "status.exact": "exact",
    "status.applying": "applying",
    "status.separating": "separating",

    "moon.New Moon": "New Moon",
    "moon.Waxing Crescent": "Waxing Crescent",
    "moon.First Quarter": "First Quarter",
    "moon.Waxing Gibbous": "Waxing Gibbous",
    "moon.Full Moon": "Full Moon",
    "moon.Waning Gibbous": "Waning Gibbous",
    "moon.Third Quarter": "Third Quarter",
    "moon.Last Quarter": "Last Quarter",
    "moon.Waning Crescent": "Waning Crescent",
]

/// The line under the feels-like label, per category and time of day. The
/// English and Russian halves of `data/feels_like_time_modifiers.json`, which
/// the web app reads directly; edits there belong here too.
private let enMood: [String: String] = [
    "mood.Calm.morning": "Gentle start ahead",
    "mood.Calm.afternoon": "Calm and steady",
    "mood.Calm.evening": "Peaceful wind-down",
    "mood.Calm.night": "Deep stillness",
    "mood.Subtle pressure.morning": "Something stirring beneath",
    "mood.Subtle pressure.afternoon": "Haze of tension",
    "mood.Subtle pressure.evening": "Undercurrent surfaces",
    "mood.Subtle pressure.night": "Restless quiet",
    "mood.Grinding.morning": "Heavy start, pace yourself",
    "mood.Grinding.afternoon": "Endurance mode",
    "mood.Grinding.evening": "Release the weight",
    "mood.Grinding.night": "Let the body recover",
    "mood.Flowing.morning": "Promising start",
    "mood.Flowing.afternoon": "In the flow",
    "mood.Flowing.evening": "Savor the harmony",
    "mood.Flowing.night": "Drift into peace",
    "mood.Dynamic.morning": "Active day building",
    "mood.Dynamic.afternoon": "Bold moves time",
    "mood.Dynamic.evening": "Process the buzz",
    "mood.Dynamic.night": "Mind still racing",
    "mood.Pressured.morning": "Brace for demands",
    "mood.Pressured.afternoon": "Adapt to pressure",
    "mood.Pressured.evening": "Decompress gently",
    "mood.Pressured.night": "Release and restore",
    "mood.Expansive.morning": "Big energy awakening",
    "mood.Expansive.afternoon": "Doors are opening",
    "mood.Expansive.evening": "Celebrate the expansion",
    "mood.Expansive.night": "Dream big tonight",
    "mood.Charged.morning": "Storm energy building",
    "mood.Charged.afternoon": "Ready to discharge",
    "mood.Charged.evening": "Let the charge settle",
    "mood.Charged.night": "Electric dreams ahead",
    "mood.Intense.morning": "Fiery day ahead",
    "mood.Intense.afternoon": "Fire and pressure",
    "mood.Intense.evening": "Cool the flames",
    "mood.Intense.night": "Let the fire die down",
    "mood.Powerful.morning": "Rare launch window",
    "mood.Powerful.afternoon": "Breakthrough energy",
    "mood.Powerful.evening": "Ride the momentum",
    "mood.Powerful.night": "Power in stillness",
    "mood.Volatile.morning": "Expect the unexpected",
    "mood.Volatile.afternoon": "Unpredictable shifts",
    "mood.Volatile.evening": "Ground after the storm",
    "mood.Volatile.night": "Turbulent dreams possible",
    "mood.Explosive.morning": "Maximum intensity day",
    "mood.Explosive.afternoon": "Everything at once",
    "mood.Explosive.evening": "Survive and reflect",
    "mood.Explosive.night": "Deep recovery needed",
]

// MARK: - Russian

private let ruUI: [String: String] = [
    // Common
    "common.done": "Готово",
    "common.cancel": "Отмена",
    "common.close": "Закрыть",
    "common.ok": "ОК",
    "common.tryAgain": "Повторить",
    "common.delete": "Удалить",
    "common.loading": "Загрузка",
    "common.today": "Сегодня",
    "common.clear": "Очистить",
    "common.notSet": "Не задан",
    "common.day.one": "день",
    "common.day.few": "дня",
    "common.day.many": "дней",
    "common.year.one": "%d год",
    "common.year.few": "%d года",
    "common.year.many": "%d лет",
    "common.change.one": "%d смена",
    "common.change.few": "%d смены",
    "common.change.many": "%d смен",

    // Settings
    "settings.title": "Настройки",
    "settings.account": "Аккаунт",
    "settings.email": "Почта",
    "settings.notSignedIn": "Вход не выполнен",
    "settings.signOut": "Выйти",
    "settings.manageAccount": "Управление аккаунтом",
    "settings.accountFooter": "Удаление убирает ваши профили, данные рождения и сам аккаунт. Отменить это нельзя.",
    "settings.deleteAccount": "Удалить аккаунт",
    "settings.deleteAccountTitle": "Удалить аккаунт?",
    "settings.deleteAccountBody": "Будут удалены ваши профили, данные рождения, подписки на других людей и сам аккаунт. Отменить это нельзя.",
    "settings.deleteAccountKeep": "Оставить аккаунт",
    "settings.deleteAccountFailed": "Не удалось удалить аккаунт",
    "settings.notifications": "Уведомления",
    "settings.categoryChanges": "Смена категории",
    "settings.openIosSettings": "Включить в настройках iOS",
    "settings.timeOfDay": "Время дня",
    "settings.scheduled": "Запланировано",
    "settings.notificationsDenied": "Уведомления для big3.me отключены в настройках iOS, поэтому запланировать их нельзя.",
    "settings.notificationsFooter": "Каждый день читается как одна из двенадцати категорий, от «Спокойно» до «Взрывоопасно». Приходит уведомление о днях, когда она сменится на другую, для профиля, отмеченного как ваш.",
    "settings.nextAlert": "Следующее",
    "settings.sendTest": "Отправить тестовое уведомление",
    "settings.testAlert": "Тестовое уведомление",
    "settings.testSent": "Придёт через несколько секунд. Выйдите с этого экрана, чтобы увидеть баннер.",
    "settings.testFailed": "Отправить не удалось. Проверьте, что уведомления для big3.me разрешены в настройках iOS.",
    "settings.appearance": "Оформление",
    "settings.theme": "Тема",
    "settings.theme.system": "Системная",
    "settings.theme.light": "Светлая",
    "settings.theme.dark": "Тёмная",
    "settings.language": "Язык",
    "settings.language.system": "Система",
    "settings.languageFooter": "«Система» берёт язык устройства. Выбор действует на всё приложение, включая веб-экраны.",
    "settings.about": "О приложении",
    "settings.version": "Версия",

    // Sign in
    "auth.subtitleEmail": "Войдите по электронной почте",
    "auth.subtitleCode": "Мы отправили код на %@",
    "auth.subtitlePassword": "Войдите с паролем",
    "auth.email": "Электронная почта",
    "auth.password": "Пароль",
    "auth.code": "Код из 6 цифр",
    "auth.sendCode": "Отправить код",
    "auth.signIn": "Войти",
    "auth.resend": "Отправить ещё раз",
    "auth.changeEmail": "Изменить адрес",
    "auth.or": "или",
    "auth.continueApple": "Продолжить с Apple",
    "auth.continueGoogle": "Продолжить с Google",
    "auth.usePassword": "Войти с паролем",
    "auth.useCode": "Войти по коду",
    "auth.checkInbox": "Проверьте почту, там код.",

    // First-run offer of the category alerts
    "offer.title": "Узнавайте, когда погода меняется",
    "offer.body": "Каждый день читается как одна из двенадцати категорий, от «Спокойно» до «Взрывоопасно». Мы скажем заранее о днях, когда она сменится на другую.",
    "offer.footnote": "Около полудня и только в те дни, когда она правда меняется.",
    "offer.accept": "Включить",
    "offer.decline": "Не сейчас",

    // Home
    "home.notSignedIn": "Вход не выполнен",
    "home.notSignedInBody": "Войдите, чтобы увидеть свой прогноз.",
    "home.openSignIn": "Открыть вход",
    "home.loadFailed": "Не удалось загрузить профили",
    "home.noProfiles": "Профилей пока нет",
    "home.noProfilesBody": "Создайте свой профиль или найдите чужой, чтобы подписаться.",
    "home.createProfile": "Создать профиль",
    "home.searchProfiles": "Поиск профилей",
    "home.allProfiles": "Все профили",
    "home.pagerPosition": "Профиль %1$d из %2$d",

    // Weather page
    "weather.editProfile": "Изменить профиль",
    "weather.unfollow": "Отписаться",
    "weather.profileOptions": "Действия с профилем",
    "weather.momentHint": "Выберите момент и место для прогноза",
    "weather.intensityLabel": "ИНТЕНСИВНОСТЬ",
    "weather.tensionLabel": "НАПРЯЖЕНИЕ",
    "weather.intensityValue": "Интенсивность %d",
    "weather.tensionA11y": "Напряжение %d процентов",
    "weather.noForecast": "Прогноза нет",
    "weather.noForecastDays": "Для этого профиля не пришло ни одного дня прогноза.",
    "weather.forecastTitle": "Прогноз на %d дней",
    "forecast.todayLong": "Сегодня, %@",
    "forecast.noTransits": "Транзитов нет",
    "forecast.noTransitsBody": "В этот день нет транзитов в пределах орба.",

    // Active transits
    "transits.title": "Активные транзиты",
    "transits.mostImpact": "Самые сильные",
    "transits.nothingStrong": "Сейчас нет точных и сильных аспектов.",
    "transits.orbA11y": "%1$@, %2$@, орб %3$@ градусов",
    "group.personal": "Персональные планеты",
    "group.outer": "Высшие планеты",
    "group.special": "Особые точки",

    // Climate
    "climate.title": "Климат",

    // Transit detail
    "detail.window": "Окно",
    "detail.positions": "Позиции",
    "detail.orb": "орб %@°",
    "detail.exactTimes": "Точный %1$d раза: %2$@",
    "detail.hours": "%d ч",
    "detail.days": "%d дн.",
    "detail.transiting": "транзитная",
    "detail.natal": "натальная",
    "detail.retrograde": "ретроград",
    "detail.house": "дом %d",

    // Moment and place
    "moment.title": "Момент",
    "moment.date": "Дата",
    "moment.time": "Время",
    "moment.place": "Место",
    "moment.searchCity": "Поиск города",
    "moment.profileOwn": "Как у профиля",
    "moment.readPresent": "Читать текущий момент",
    "moment.readThis": "Читать этот момент",

    // Moon
    "moon.illumination": "Освещённость",
    "moon.sign": "Луна в знаке",
    "moon.fullMoon": "Полнолуние",
    "moon.newMoon": "Новолуние",
    "moon.nextFullMoon": "След. полнолуние",

    // Natal chart card
    "natal.title": "Астропрофиль",
    "natal.expand": "Показывает остальной профиль",
    "natal.collapse": "Скрывает остальной профиль",

    // Chart wheel
    "chart.title": "Карта рождения",
    "wheel.natal": "Рождение",
    "wheel.transit": "Транзит",
    "chart.wheelA11y": "Колесо карты рождения",
    "chart.specialPoints": "Особые точки",
    "chart.tapHint": "Нажмите на планету или линию",
    "chart.tapHintZoom": "Нажмите на планету или линию · щипок для зума",
    "chart.openFullScreen": "Открыть карту на весь экран",
    "chart.fit": "Показать карту целиком",
    "chart.transit": "Транзит",
    "chart.natal": "Карта",
    "chart.house": "Дом %d",
    "chart.orb": "орб %@",

    // Profile list
    "profiles.searchPrompt": "Поиск профилей",
    "profiles.mine": "Мои",
    "profiles.new": "Новый профиль",
    "profiles.following": "Подписки",
    "profiles.primary": "Основной",
    "profiles.primaryA11y": "Основной профиль",
    "profiles.none": "Профилей пока нет.",
    "profiles.noMatch": "Ничего не найдено по «%@».",
    "profiles.noReading": "Прогноза пока нет",

    // Profile search
    "search.title": "Поиск",
    "search.discover": "Интересное",
    "search.new": "Новые профили",
    "search.searching": "Поиск…",
    "search.hint": "Найдите профиль по имени или @нику.",
    "search.followError": "Не удалось подписаться",
    "search.subscribeTo": "Подписаться на %@",
    "search.clear": "Очистить поиск",
    "search.close": "Закрыть поиск",

    // Profile preview
    "preview.bigThree": "Большая тройка",
    "preview.born": "Рождение",

    // Profile edit
    "edit.title": "Изменить профиль",
    "edit.newTitle": "Новый профиль",
    "edit.save": "Сохранить профиль",
    "edit.name": "Имя",
    "edit.fullName": "Полное имя",
    "edit.username": "Ник",
    "edit.usernamePlaceholder": "ник",
    "edit.date": "Дата",
    "edit.time": "Время",
    "edit.birthplace": "Место рождения",
    "edit.birthplacePlaceholder": "Город, страна",
    "edit.pickPlace": "Выберите место из списка или сохраните, и мы найдём его сами.",
    "edit.coordinates": "Координаты и часовой пояс",
    "edit.coordinatesFooter": "Они берутся из выбранного места рождения, поэтому их не нужно вводить вручную.",
    "edit.timezone": "Часовой пояс",
    "edit.latitude": "Широта",
    "edit.longitude": "Долгота",
    "edit.loadFailed": "Не удалось загрузить профиль",
    "edit.deleteTitle": "Удалить этот профиль?",
    "edit.deleteBody": "«%@» и его натальная карта будут удалены навсегда. Отменить это нельзя.",
    "edit.deleteButton": "Удалить профиль",
    "edit.resolveFailed": "Не удалось найти «%@». Выберите место из списка.",

    // Transfer a profile to someone else
    "transfer.title": "Передать профиль",
    "transfer.sendTo": "Кому",
    "transfer.emailPlaceholder": "recipient@example.com",
    "transfer.profile": "Профиль",
    "transfer.footer": "Ему придёт письмо со ссылкой. Профиль остаётся вашим, пока он не войдёт и не примет его.",
    "transfer.send": "Отправить приглашение",
    "transfer.sending": "Отправка",
    "transfer.sent": "Приглашение отправлено",
    "transfer.created": "Приглашение создано",
    "transfer.sentBody": "%1$@ теперь может принять «%2$@». Профиль остаётся вашим, пока это не произойдёт.",
    "transfer.createdBody": "Письмо отправить не удалось, передайте ссылку сами. Она примет «%@» для того, кто её откроет.",
    "transfer.copyLink": "Скопировать ссылку",
    "transfer.linkCopied": "Ссылка скопирована",
    "transfer.shareLink": "Поделиться ссылкой",

    // Category-change notifications
    "alert.rising": "Растёт",
    "alert.easing": "Спадает",
    "alert.shifting": "Меняется",
    "alert.body": "%1$@, было «%2$@»",

    // Errors
    "error.notSignedIn": "Войдите, чтобы загрузить профили.",
    "error.unexpected": "Сервер вернул неожиданный ответ.",
    "error.cancelled": "Запрос отменён.",
    "error.googleNoSession": "Вход через Google завершился без сессии.",
    "error.appleNoToken": "Apple не вернула токен для входа.",
    "error.http": "Запрос не удался (HTTP %d).",
    "error.tooMany": "Слишком много попыток. Подождите минуту и попробуйте снова.",
    "error.badDetails": "Не получилось. Проверьте данные и попробуйте снова.",
    "error.noURL": "Не удалось построить URL для %@.",
]

private let ruAstro: [String: String] = [
    "feels.Calm": "Спокойно",
    "feels.Subtle pressure": "Лёгкое давление",
    "feels.Grinding": "Тяжесть",
    "feels.Flowing": "Поток",
    "feels.Dynamic": "Динамично",
    "feels.Pressured": "Под давлением",
    "feels.Expansive": "Расширение",
    "feels.Charged": "Заряжено",
    "feels.Intense": "Интенсивно",
    "feels.Powerful": "Мощно",
    "feels.Volatile": "Нестабильно",
    "feels.Explosive": "Взрывоопасно",

    "planet.Sun": "Солнце",
    "planet.Moon": "Луна",
    "planet.Mercury": "Меркурий",
    "planet.Venus": "Венера",
    "planet.Mars": "Марс",
    "planet.Jupiter": "Юпитер",
    "planet.Saturn": "Сатурн",
    "planet.Uranus": "Уран",
    "planet.Neptune": "Нептун",
    "planet.Pluto": "Плутон",
    "planet.Chiron": "Хирон",
    "planet.Lilith": "Лилит",
    "planet.Selena": "Селена",
    "planet.North Node": "Сев. узел",
    "planet.South Node": "Юж. узел",
    "planet.Part of Fortune": "Жребий Фортуны",
    "planet.Vertex": "Вертекс",
    "planet.ASC": "Асцендент",
    "planet.MC": "Середина Неба",

    "sign.Aries": "Овен",
    "sign.Taurus": "Телец",
    "sign.Gemini": "Близнецы",
    "sign.Cancer": "Рак",
    "sign.Leo": "Лев",
    "sign.Virgo": "Дева",
    "sign.Libra": "Весы",
    "sign.Scorpio": "Скорпион",
    "sign.Sagittarius": "Стрелец",
    "sign.Capricorn": "Козерог",
    "sign.Aquarius": "Водолей",
    "sign.Pisces": "Рыбы",

    "aspect.conjunction": "соединение",
    "aspect.opposition": "оппозиция",
    "aspect.trine": "трин",
    "aspect.square": "квадрат",
    "aspect.sextile": "секстиль",

    "strength.exact": "ТОЧНЫЙ",
    "strength.strong": "СИЛЬНЫЙ",
    "strength.moderate": "УМЕРЕННЫЙ",
    "strength.wide": "СЛАБЫЙ",

    "status.exact": "точный",
    "status.applying": "сходится",
    "status.separating": "расходится",

    "moon.New Moon": "Новолуние",
    "moon.Waxing Crescent": "Растущий серп",
    "moon.First Quarter": "Первая четверть",
    "moon.Waxing Gibbous": "Растущая Луна",
    "moon.Full Moon": "Полнолуние",
    "moon.Waning Gibbous": "Убывающая Луна",
    "moon.Third Quarter": "Третья четверть",
    "moon.Last Quarter": "Последняя четверть",
    "moon.Waning Crescent": "Убывающий серп",
]

private let ruMood: [String: String] = [
    "mood.Calm.morning": "Мягкое начало дня",
    "mood.Calm.afternoon": "Спокойно и ровно",
    "mood.Calm.evening": "Спокойный вечер",
    "mood.Calm.night": "Глубокая тишина",
    "mood.Subtle pressure.morning": "Что-то шевелится внутри",
    "mood.Subtle pressure.afternoon": "Лёгкая дымка напряжения",
    "mood.Subtle pressure.evening": "Подводное течение всплывает",
    "mood.Subtle pressure.night": "Беспокойная тишина",
    "mood.Grinding.morning": "Тяжёлое начало, не спеши",
    "mood.Grinding.afternoon": "Режим выносливости",
    "mood.Grinding.evening": "Отпусти тяжесть",
    "mood.Grinding.night": "Дай телу восстановиться",
    "mood.Flowing.morning": "Многообещающее начало",
    "mood.Flowing.afternoon": "В потоке",
    "mood.Flowing.evening": "Насладись гармонией",
    "mood.Flowing.night": "Уплывай в покой",
    "mood.Dynamic.morning": "Активный день нарастает",
    "mood.Dynamic.afternoon": "Время смелых шагов",
    "mood.Dynamic.evening": "Переработай впечатления",
    "mood.Dynamic.night": "Мысли ещё гудят",
    "mood.Pressured.morning": "Готовься к нагрузке",
    "mood.Pressured.afternoon": "Адаптируйся к давлению",
    "mood.Pressured.evening": "Мягко сбрось давление",
    "mood.Pressured.night": "Отпусти и восстановись",
    "mood.Expansive.morning": "Большая энергия просыпается",
    "mood.Expansive.afternoon": "Двери открываются",
    "mood.Expansive.evening": "Отпразднуй расширение",
    "mood.Expansive.night": "Мечтай масштабно",
    "mood.Charged.morning": "Энергия грозы нарастает",
    "mood.Charged.afternoon": "Готово к разрядке",
    "mood.Charged.evening": "Дай заряду осесть",
    "mood.Charged.night": "Электрические сны впереди",
    "mood.Intense.morning": "Огненный день впереди",
    "mood.Intense.afternoon": "Огонь и давление",
    "mood.Intense.evening": "Остуди пламя",
    "mood.Intense.night": "Дай огню угаснуть",
    "mood.Powerful.morning": "Редкое окно запуска",
    "mood.Powerful.afternoon": "Энергия прорыва",
    "mood.Powerful.evening": "Используй импульс",
    "mood.Powerful.night": "Сила в покое",
    "mood.Volatile.morning": "Жди неожиданного",
    "mood.Volatile.afternoon": "Непредсказуемые сдвиги",
    "mood.Volatile.evening": "Заземлись после бури",
    "mood.Volatile.night": "Возможны бурные сны",
    "mood.Explosive.morning": "День максимальной интенсивности",
    "mood.Explosive.afternoon": "Всё сразу",
    "mood.Explosive.evening": "Выдохни и осмысли",
    "mood.Explosive.night": "Нужно глубокое восстановление",
]
