import UIKit

/// The temperature card that rides along with the daily notification.
///
/// iOS will not let an app replace the badge at the leading edge of a banner —
/// that one is the system's, and it is always the app icon, drawn small. What
/// it does allow is an attachment, which it shows as the notification's own
/// thumbnail next to the text and full width once the banner is expanded. So
/// the reading travels as a picture: a pastel gradient chosen for the category
/// with the temperature on it, which is the part worth looking at.
enum CategoryArtwork {

    /// A pastel ramp and the ink that stays legible on it.
    ///
    /// One per category rather than one per TII zone: four skies would put
    /// `Calm` and `Grinding` on the same blue, and the category is what the
    /// notification is announcing.
    struct Palette {
        let stops: [UInt32]
        let ink: UInt32
    }

    /// Twelve hues for twelve categories, ordered the way the TII × tension
    /// matrix orders them — cool and quiet through to hot and violent — and
    /// kept in separate hue families so no two are mistaken at thumbnail size.
    static func palette(for category: String) -> Palette {
        switch category {
        // Low TII
        case "Calm":
            return Palette(stops: [0xE3EDFF, 0xC3D6F7, 0xA8C3EF], ink: 0x27406F)
        case "Subtle pressure":
            return Palette(stops: [0xE9E5FB, 0xCEC6F1, 0xB8ADE8], ink: 0x3A3072)
        case "Grinding":
            return Palette(stops: [0xEBE3E9, 0xD2C2CD, 0xBEAAB8], ink: 0x453541)

        // Mid TII
        case "Flowing":
            return Palette(stops: [0xE0F8EF, 0xB8E9D6, 0x9BDDC5], ink: 0x0F5B44)
        case "Dynamic":
            return Palette(stops: [0xDCF4F8, 0xB0E2EC, 0x93D5E3], ink: 0x0D4E59)
        case "Pressured":
            return Palette(stops: [0xF6E7E6, 0xE1C3C2, 0xD2ADAC], ink: 0x633636)

        // High TII
        case "Expansive":
            return Palette(stops: [0xFFF2D8, 0xFBD9A5, 0xF7C983], ink: 0x74490F)
        case "Charged":
            return Palette(stops: [0xFFE5DC, 0xFBB9A6, 0xF8A28C], ink: 0x852F22)
        case "Intense":
            return Palette(stops: [0xFFE0E0, 0xF8A9A9, 0xF39191], ink: 0x852323)

        // Extreme TII
        case "Powerful":
            return Palette(stops: [0xFFF4CE, 0xF6D585, 0xF1C662], ink: 0x6B4907)
        case "Volatile":
            return Palette(stops: [0xFCE4F6, 0xF0B8E1, 0xE9A3D6], ink: 0x6E2164)
        case "Explosive":
            return Palette(stops: [0xFFE2DC, 0xF5A9AE, 0xDC8FBE], ink: 0x741C3C)

        // A label the engine grew after this shipped: neutral, never wrong.
        default:
            return Palette(stops: [0xECECEF, 0xD3D3D9, 0xC1C1C9], ink: 0x3A3A40)
        }
    }

    /// Renders the card and writes it where `UNNotificationAttachment` can
    /// take it.
    ///
    /// The attachment *moves* the file into its own store, so every call gets
    /// a filename of its own — handing the same URL over twice fails the
    /// second time, and the schedule is rebuilt on every foreground.
    static func file(for day: DailyAlert) -> URL? {
        let image = render(temperature: day.tii, category: day.to)
        // JPEG, not PNG: the card is a smooth gradient, which PNG stores badly
        // — 200KB against 20KB for something the eye cannot tell apart — and
        // the thumbnail is generated by QuickLook, which is happiest with the
        // format it sees most.
        guard let data = image.jpegData(compressionQuality: 0.9) else {
            NSLog("[Alerts] could not encode the artwork for \(day.date)")
            return nil
        }

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("category-\(day.date)-\(UUID().uuidString).jpg")

        do {
            try data.write(to: url)
            return url
        } catch {
            NSLog("[Alerts] could not write the artwork for \(day.date): \(error.localizedDescription)")
            return nil
        }
    }

    /// Square, because that is the shape iOS crops the banner's thumbnail to.
    private static let side: CGFloat = 512

    static func render(temperature: Double, category: String) -> UIImage {
        let palette = palette(for: category)
        let rect = CGRect(x: 0, y: 0, width: side, height: side)

        // Pinned to 1x and opaque, rather than left on the renderer's defaults.
        // At the screen's own scale this comes out 1536² with an alpha channel
        // and near two megabytes, and QuickLook — which is what actually draws
        // the banner's thumbnail — answers `QLThumbnailErrorDomain 102` for it
        // and the card silently does not appear. 512² opaque is a fiftieth of
        // the bytes and still four times the size it is shown at.
        let format = UIGraphicsImageRendererFormat.default()
        format.scale = 1
        format.opaque = true

        return UIGraphicsImageRenderer(size: rect.size, format: format).image { context in
            let cgContext = context.cgContext

            // Diagonal, matching the profile cards in the list: a straight
            // top-to-bottom ramp reads as flat at 38pt.
            if let gradient = CGGradient(
                colorsSpace: CGColorSpaceCreateDeviceRGB(),
                colors: palette.stops.map { UIColor(hex: $0).cgColor } as CFArray,
                locations: [0, 0.55, 1]
            ) {
                cgContext.drawLinearGradient(
                    gradient,
                    start: .zero,
                    end: CGPoint(x: side, y: side),
                    options: []
                )
            }

            // A soft highlight in the top-left corner, so the square has some
            // depth instead of reading as a flat swatch.
            if let sheen = CGGradient(
                colorsSpace: CGColorSpaceCreateDeviceRGB(),
                colors: [
                    UIColor.white.withAlphaComponent(0.55).cgColor,
                    UIColor.white.withAlphaComponent(0).cgColor,
                ] as CFArray,
                locations: [0, 1]
            ) {
                cgContext.drawRadialGradient(
                    sheen,
                    startCenter: CGPoint(x: side * 0.24, y: side * 0.18),
                    startRadius: 0,
                    endCenter: CGPoint(x: side * 0.24, y: side * 0.18),
                    endRadius: side * 0.72,
                    options: []
                )
            }

            // Rounded rather than the app's Space Grotesk: this is drawn at
            // 512 and shown at 38, and the system's rounded numerals hold
            // their shape at that reduction where a display face does not.
            // Medium rather than the hero's ultraLight for the same reason.
            let size = side * 0.42
            let base = UIFont.systemFont(ofSize: size, weight: .medium)
            let font = UIFont(
                descriptor: base.fontDescriptor.withDesign(.rounded) ?? base.fontDescriptor,
                size: size
            )

            let text = "\(Int(temperature.rounded()))" as NSString
            let attributes: [NSAttributedString.Key: Any] = [
                .font: font,
                .foregroundColor: UIColor(hex: palette.ink),
                .kern: -size * 0.03,
            ]

            let measured = text.size(withAttributes: attributes)
            text.draw(
                at: CGPoint(
                    x: (side - measured.width) / 2,
                    y: (side - measured.height) / 2
                ),
                withAttributes: attributes
            )
        }
    }
}

private extension UIColor {
    convenience init(hex: UInt32) {
        self.init(
            red: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
}
