from __future__ import annotations

from typing import Any, Protocol


class ChartRepository(Protocol):
    def save_chart(self, chart: dict[str, object], chart_id: str | None = None) -> tuple[str, str]: ...
    def load_chart(self, chart_id: str) -> tuple[str, dict[str, object]]: ...


class ProfileRepository(Protocol):
    def list_summaries(self, *, user_id: str | None = None) -> list[dict[str, Any]]: ...
    def load_profile(self, profile_id: str) -> dict[str, Any]: ...
    def load_profile_with_social(self, profile_id: str, viewer_user_id: str) -> dict[str, Any]: ...
    def create_profile(
        self,
        profile_name: str,
        username: str,
        chart_id: str,
        *,
        user_id: str | None = None,
        profile_input: dict[str, object] | None = None,
        profile_id: str | None = None,
        created_at: str | None = None,
        updated_at: str | None = None,
    ) -> dict[str, Any]: ...
    def update_profile(
        self,
        profile_id: str,
        profile_name: str,
        username: str,
        chart_id: str,
        *,
        profile_input: dict[str, object] | None = None,
    ) -> dict[str, Any]: ...
    def delete_profile(self, profile_id: str) -> None: ...
    def resolve_profile_chart_id(self, profile_id: str) -> str: ...
    def delete_chart_if_unreferenced(self, chart_id: str, *, exclude_profile_id: str | None = None) -> None: ...
    def save_latest_transit(self, profile_id: str, latest_transit: dict[str, Any]) -> dict[str, Any]: ...
    def list_featured(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def set_featured(self, profile_id: str, featured: bool) -> None: ...
    def search_public(self, query: str, *, limit: int = 20) -> list[dict[str, Any]]: ...
    def follow_profile(self, user_id: str, profile_id: str) -> bool: ...
    def unfollow_profile(self, user_id: str, profile_id: str) -> None: ...
    def list_followed(self, user_id: str) -> list[dict[str, Any]]: ...
    def is_following(self, user_id: str, profile_id: str) -> bool: ...
    def get_primary_profile_id(self, user_id: str) -> str | None: ...
    def set_primary_profile_id(self, user_id: str, profile_id: str) -> None: ...
    def set_primary_if_first_profile(self, user_id: str, profile_id: str) -> bool: ...
    def get_profile_arrangement(self, user_id: str) -> dict[str, list[str]]: ...
    def set_profile_arrangement(
        self, user_id: str, *, favorite_profile_ids: list[str], profile_order: list[str]
    ) -> None: ...
    def create_invite(
        self, profile_id: str, invited_email: str, token: str, invited_by: str, expires_at: Any
    ) -> dict[str, Any]: ...
    def get_invite_by_token(self, token: str) -> dict[str, Any] | None: ...
    def accept_invite(self, token: str, new_user_id: str) -> dict[str, Any]: ...


class SocialRepository(Protocol):
    def like_profile(
        self, user_id: str, profile_id: str, *, feels_like: str | None = ..., tii: float | None = ...
    ) -> bool: ...
    def unlike_profile(self, user_id: str, profile_id: str, *, feels_like: str | None = ...) -> None: ...
    def social_counts(self, profile_ids: list[str], viewer_user_id: str) -> dict[str, dict[str, Any]]: ...
    def followers_among(self, viewer_user_id: str, user_ids: set[str]) -> set[str]: ...
    def follows_viewer(self, owner_user_id: str, viewer_user_id: str) -> bool: ...
    def list_likers(self, profile_id: str, viewer_user_id: str) -> list[dict[str, Any]]: ...
    def list_followers(self, profile_id: str, viewer_user_id: str) -> list[dict[str, Any]]: ...
    def list_activity(self, user_id: str, *, limit: int = ...) -> dict[str, Any]: ...
    def unread_activity_count(self, user_id: str) -> int: ...
    def mark_activity_seen(self, user_id: str) -> None: ...
    def social_settings(self, user_id: str) -> dict[str, bool]: ...
    def update_social_settings(
        self,
        user_id: str,
        *,
        show_counts: bool | None = ...,
        push_likes: bool | None = ...,
        push_follows: bool | None = ...,
        push_messages: bool | None = ...,
    ) -> dict[str, bool]: ...
    def card_for(self, user_id: str) -> dict[str, Any]: ...
    def register_device(self, user_id: str, token: str, *, environment: str, lang: str) -> None: ...
    def unregister_device(self, user_id: str, token: str) -> None: ...
    def devices_for(self, user_id: str) -> list[dict[str, str]]: ...
    def drop_device(self, token: str) -> None: ...
    def block_user(self, blocker_id: str, blocked_id: str) -> None: ...
    def unblock(self, blocker_id: str, block_id: int) -> bool: ...
    def list_blocks(self, blocker_id: str) -> list[dict[str, Any]]: ...
    def blocked_user_ids(self, user_id: str) -> set[str]: ...
    def blocker_of(self, viewer_id: str, other_id: str) -> str | None: ...
    def create_report(
        self, reporter_id: str, profile: dict[str, Any], *, reason: str, details: str | None
    ) -> dict[str, Any]: ...


class ChatRepository(Protocol):
    def open_chat(self, user_id: str, peer_id: str) -> dict[str, Any]: ...
    def peer_of(self, user_id: str, chat_id: int) -> str: ...
    def primary_profile_of(self, user_id: str) -> str | None: ...
    def list_chats(self, user_id: str, *, limit: int = ...) -> dict[str, Any]: ...
    def list_messages(
        self, user_id: str, chat_id: int, *, before: int | None = ..., after: int | None = ..., limit: int = ...
    ) -> dict[str, Any]: ...
    def send_message(self, user_id: str, chat_id: int, body: str) -> dict[str, Any]: ...
    def mark_read(self, user_id: str, chat_id: int, up_to: int | None = ...) -> int: ...
    def unread_count(self, user_id: str) -> int: ...
    def contacts(self, user_id: str) -> list[dict[str, Any]]: ...


class LocationCacheRepository(Protocol):
    def get(self, query: str) -> dict[str, Any] | None: ...
    def put(self, query: str, payload: dict[str, Any]) -> dict[str, Any]: ...
